#66 roles claims actions
book-hub-umsp/book-hub-api pull request #113
Opened 2024-11-16 18:06 UTC by Tigeroff2002

Попробовал добавить систему с ролями и клэймами, про которую говорили
Роль - является отдельной сущностью в БД - и представляет собой название какое то и набор клэймов
Клэймы я решил сделать через енамы - так как никакого профита от того, что они будут сущностью в БД - я не вижу

В стартовой миграции я провел data feed с возможными ролями и их клэймами. 
Накидал roles service, roles repository и контроллер админа - в котором policy для отдельных методов определяется через Claim - сделал специальный middleware хэндлер - определящий по роли существующего пользователя, обладает ли он необходимым клэймом - если нет - то вернется 403

Пришлось сделать словарь с сопоставлением енамов на строки - так как атрибуты требуют константных значений

Миграции протестил, запросы пока не получилось полностью - так как не разобрался с регистрацией - получаю 401 на каждый запрос

resolved #66

2024-11-16 18:21 UTC, wi1sp commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
мне кажется делать клеймом енамом не надо тк будут добавляться новые при появлении новых функций в системе

2024-11-16 18:25 UTC, wi1sp commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
ну хотя вроде можно `ALTER TYPE ADD VALUE` писать так что наверное не критично

2024-11-16 18:30 UTC, wi1sp commented on BookHub.Models/Account/ClaimType.cs
> +    None,
не понял зачем `None` нужен

2024-11-16 19:02 UTC, Tigeroff2002 commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
Нет никакой выгоды от сущности. Потому что наличие сущности из нового тебе даёт возможность только из АПИ метода создать новую опцию. Но при этом ты создал опцию, которую ты никак по коду не применишь - тебе все равно надо тикет создавать на использование клэйма в АПИ
Проще уж тогда просто расширять тип енама

2024-11-16 20:42 UTC, AlexBimlnk commented
Я против того, чтобы называть это Claim и путать с аналогичными сущностями из авторизации и пр..
Назовите это permissions @wi1sp @Tigeroff2002

2024-11-16 22:06 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
это слишком... Нам просто незачем делить так возможности.
Мы обсуждали что будем делить их на большие фичи.
Я бы оставил просто сейчас отдельной возможностью moderate и всё. Это просто лишние сложности ненужные.

2024-11-16 22:07 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                    x => updatedRole.CompareTo(new(x.Name)),
че за бред, у нас у роли ID есть

2024-11-16 22:08 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +        MailAddress mailAddress,
Почему не юзер Id?

2024-11-16 22:09 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +            .Select(x => new { x.Email, x.Role })
x => x.Role

2024-11-16 22:10 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
Сейчас нет никакой выгоды и резона делать настолько гранулярные решения. И тем более их поддерживать..

2024-11-16 22:12 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
Если поймем что нужно - расширим. А пока нужен просто permission разрешающий модерацию контента (content_moderation). И возможно еще один - на модерацию пользовательских аккаунтов (account_moderation).
И сейчас этого хватит за глаза

2024-11-16 22:12 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
И не думаю что супер админ нужен в принципе

2024-11-16 22:12 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +        Name<Role> clarifiedRoleName,
Id

2024-11-16 22:13 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('moderator', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility"}');
чет я не припомню чтобы таким синтаксисом добавляли массив...

2024-11-16 22:16 UTC, AlexBimlnk commented on BookHub.API/Roles/Claims.cs
> +    private static readonly Dictionary<ClaimType, string> _claimsMapping =
а зачем это вообще не понял??

2024-11-16 22:18 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +        foreach (var claim in Enum.GetValues<ClaimType>())
для этого совершенно необязательно метод целый создавать

2024-11-16 22:22 UTC, AlexBimlnk commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +    Task AddRoleAsync(Role role, CancellationToken token);
не думаю что это нужно

2024-11-16 22:24 UTC, AlexBimlnk commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +}
нужен метод получения всех пермишенов 
Чтобы из них выбирать те, что обновить для роли

2024-11-16 22:25 UTC, AlexBimlnk commented on BookHub.Models/Account/Role.cs
> +{
Id

2024-11-16 22:26 UTC, AlexBimlnk commented on BookHub.Models/Account/Role.cs
> +{
И зачем вообще здесь IEquatable<Role>

2024-11-16 22:26 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksHubContext.cs
> +           .WithMany()
указать явно

2024-11-16 22:27 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +    public async Task AddRoleAsync(Role role, CancellationToken token)
не надо

2024-11-16 22:31 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
> +    [Authorize(Policy = Claims.CHANGE_USER_ROLE)]
Policy = nameof(ClaimsType.Moderate)

2024-11-16 22:33 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                Claims.GetStringClaim(claimType),
claimType.ToString()??

2024-11-16 22:35 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
> +            _logger.LogInformation("Request was processed with failed result");
не нужен

2024-11-16 22:36 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
> +    [Route("users/changeRole")]
users/role/{roleId}

2024-11-16 22:37 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
По возможности нужно стараться избегать создания миллиона классов. И понимать что может быть один рут на разные хедеры (get/post/patch). Собственно эти хедеры уже сами говорят о том что будет делаться (обновление, получение добавление), поэтому прописывать это в uri не нужно

2024-11-16 22:39 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
> +    [Route("roles/changeClaims")]
roles/?roleId=1&claims=

2024-11-16 22:41 UTC, AlexBimlnk commented on BookHub.API/Roles/ClaimTypeRequirement.cs
> +public sealed class ClaimTypeRequirement : IAuthorizationRequirement
сделать структурой может быть?

2024-11-16 22:41 UTC, AlexBimlnk commented on BookHub.API/Roles/ClaimTypeRequirement.cs
> +public sealed class ClaimTypeRequirement : IAuthorizationRequirement
readonly record struct?

2024-11-16 22:42 UTC, AlexBimlnk commented on BookHub.Models/Account/ClaimType.cs
> +public enum ClaimType
Permission

2024-11-17 07:35 UTC, wi1sp commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
Проблема не в сущности, а в том что енам периодческт апдейтить надо, что не очень хорошо

2024-11-17 07:38 UTC, wi1sp commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('moderator', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility"}');
не нормально это так работает

2024-11-17 13:08 UTC, Tigeroff2002 commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
А какая разница в том что делать - ENUM ADD VALUE или INSERT INTO TABLE?

2024-11-17 13:08 UTC, Tigeroff2002 commented on BookHub.Models/Account/ClaimType.cs
> +    None,
Решил, что пусть будет пустой клэйм - может как заглушка понадобится - дефолт значения для енама держать - нормальная практика

2024-11-17 13:09 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                    x => updatedRole.CompareTo(new(x.Name)),
По айди ты никак нормально запрос не сделаешь - у тебя есть имя, фронт только его имеет. Айди нужен просто для целостности БД

2024-11-17 13:10 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +        MailAddress mailAddress,
Потому что в контексте email я только мог найти

2024-11-17 13:10 UTC, Tigeroff2002 commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('moderator', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility"}');
Миграция работает

2024-11-17 13:11 UTC, Tigeroff2002 commented on BookHub.API/Roles/Claims.cs
> +    private static readonly Dictionary<ClaimType, string> _claimsMapping =
Я выше написал зачем
_Пришлось сделать словарь с сопоставлением енамов на строки - так как атрибуты требуют константных строковых значений_

2024-11-17 13:11 UTC, Tigeroff2002 commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +    Task AddRoleAsync(Role role, CancellationToken token);
Пусть будет для примера

2024-11-17 13:11 UTC, Tigeroff2002 commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +}
Ну такой метод будет чуть дальше - он просто Enum.GetValues сделает

2024-11-17 13:12 UTC, Tigeroff2002 commented on BookHub.Models/Account/Role.cs
> +{
Чтобы роль по имени сравнивать можно было

2024-11-17 13:12 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/BooksHubContext.cs
> +           .WithMany()
и так достаточно думаю

2024-11-17 13:12 UTC, Tigeroff2002 commented on BookHub.API/Controllers/AdminController.cs
> +            _logger.LogInformation("Request was processed with failed result");
пусть везде будут - стандарт

2024-11-17 13:13 UTC, Tigeroff2002 commented on BookHub.API/Controllers/AdminController.cs
> +    [Route("users/changeRole")]
Не хочу я встраивать параметры в запрос. Тут их 2 к тем более

2024-11-17 13:14 UTC, Tigeroff2002 commented on BookHub.API/Controllers/AdminController.cs
> +    [Route("roles/changeClaims")]
Httput запрос может иметь тело

2024-11-17 13:14 UTC, Tigeroff2002 commented on BookHub.API/Roles/ClaimTypeRequirement.cs
> +public sealed class ClaimTypeRequirement : IAuthorizationRequirement
выгоды не вижу особо

2024-11-17 13:15 UTC, Tigeroff2002 commented on BookHub.Models/Account/ClaimType.cs
> +public enum ClaimType
Мне больше нравится нэйминг Claim. И Семен тоже самое предложил

2024-11-17 13:43 UTC, wi1sp commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
в случае енама - это DDL
в случае таблицы - DML

2024-11-17 13:54 UTC, wi1sp commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
Ладно NVM аффектиться при таких операциях только таблица ролей так, что наверное без разницы

2024-11-17 13:58 UTC, wi1sp commented on BookHub.Models/Account/ClaimType.cs
> +public enum ClaimType
немного почитал 
https://learn.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-8.0

всё таки клеймом обзывают немног не то что я имел ввиду, так что название персимжен +- более коректное название

2024-11-17 14:15 UTC, Tigeroff2002 commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
Если сделать permission (claim) как сущность в БД - то я не знаю можно ли вообще добавить AddPolicy в регистрацию - так как это не какое то значение заранее известное

2024-11-17 14:16 UTC, Tigeroff2002 commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
Тебя вообще никто не заставляет сейчас пддерживать каждый permission - это пример. Пока они никак в коде и миграции не мешает
Super admin - это просто роль грубо говоря с любыми permissions - потому что те же админы не должны мочь некоторые действия модератора

2024-11-17 14:17 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +        MailAddress mailAddress,
Окей, сделал как то через айди

2024-11-17 14:17 UTC, Tigeroff2002 commented on BookHub.API/Roles/Claims.cs
> +    private static readonly Dictionary<ClaimType, string> _claimsMapping =
Не понятно почему, но nameof он считает константой, а $"{}" - не считает.

2024-11-17 14:18 UTC, Tigeroff2002 commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +}
Добавил в отдельный контроллер

2024-11-17 14:18 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/BooksHubContext.cs
> +           .WithMany()
Ладно, указал. Хотя учитывая что у Role не было Users поля - оно бы нормально работало

2024-11-17 14:19 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +    public async Task AddRoleAsync(Role role, CancellationToken token)
Пусть будет - как я понял, такое усложнение с сущностями ролей только и предлагалось чтобы можно было бы их динамически добавлять/расширять permissions

2024-11-17 14:19 UTC, Tigeroff2002 commented on BookHub.API/Roles/Claims.cs
> +public record struct Claims
Окей пусть будет Permission
Claim - это скорее Permission_TYPE в контексте приложения

2024-11-17 14:46 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +CREATE TYPE claim_type as ENUM ('none', 'moderate_comments', 'moderate_reviews', 'create_topics', 'change_book_visibility', 'manage_user_actions', 'manage_user_accounts', 'change_user_role', 'add_new
Там уже очень много JION будет как по мне. А импакт какой-то незаметный. Я бы пока оставил как массив permissions

2024-11-17 14:47 UTC, AlexBimlnk commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
Супер админ, это просто чел с токеном в доступ в базу. Его вообще не надо на уровень приложения тащить.
На уровне приложения достаточно модеров юзеров и админов. И это уже за глаза. И админы нужны только для того, чтобы удобно ручками менять модерки по сути и всё.

2024-11-17 14:47 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                    x => updatedRole.CompareTo(new(x.Name)),
Так отдай на фронт список ролей вместе с их Id - и всё

2024-11-17 14:48 UTC, AlexBimlnk commented on BookHub.API/Roles/Claims.cs
> +    private static readonly Dictionary<ClaimType, string> _claimsMapping =
Потому что nameof известен при комплиции, а значение интерполяции может быть что угодно

2024-11-17 14:49 UTC, AlexBimlnk commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +    Task AddRoleAsync(Role role, CancellationToken token);
Не надо, уберите это пожалуйста. Нам не нужны менеджрить роли от слова совсем. Только их пермишены. И это уже оверхед небольшой предложенный DBA

2024-11-17 14:50 UTC, AlexBimlnk commented on BookHub.Models/Account/Role.cs
> +{
Зачем их вообще сравнивать? Они просто будут в базе и не будут меняться никогда

2024-11-17 14:50 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +    public async Task AddRoleAsync(Role role, CancellationToken token)
Так ты динамечески меняешь permissions для роли. А не создаешь "новые роли". Роли как были так и останутся. А вот менять их разрешения можно динамически

2024-11-17 14:51 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
> +            _logger.LogInformation("Request was processed with failed result");
(везде убрать) = стандарт

2024-11-17 14:52 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminController.cs
> +    [Route("users/changeRole")]
Вот именно. Их всего лишь 2. И зачем городить целую модель когда можно этого не делать. Усложнять запрос его телом, конвертацией в json и так далее. Когда у нас есть более удобные и легковесные инструменты придуманные как раз для таких случаев

2024-11-17 14:54 UTC, AlexBimlnk commented on BookHub.Models/Account/ClaimType.cs
> +public enum ClaimType
Архитектор победил

2024-11-17 14:55 UTC, AlexBimlnk commented on BookHub.API/Controllers/PermissionsController.cs
> +    /// Получает все permissions в системе.
неверно

2024-11-17 14:56 UTC, AlexBimlnk commented on BookHub.API/Controllers/PermissionsController.cs
> +        if (userRole is null)
Мы получаем null роль, что означает судя по сообщению ниже не отсутствие роли а отсутствие пользователя.
Это контринтуитивно. Лучше при отсутствии кидай просто IOE и перехватывай здесь.

2024-11-17 15:00 UTC, AlexBimlnk commented on BookHub.API/PermissionsHandling/PermissionTypeAuthorizationHandler.cs
> +        var userId = context.User.FindFirstValue(Auth.ClaimTypes.USER_ID_CLAIM_NAME);
Почему не использовать просто существующий Identity фасад? Он для этих случаев уже и был написан, чтобы не нужно было Convert никакие делать и логику с Find не писать

2024-11-17 15:01 UTC, AlexBimlnk commented on BookHub.API/PermissionsHandling/PermissionTypeAuthorizationHandler.cs
> +
Мы можем сначала попытаться найти пользователя, через Find с загрузкой его в контекст, потом сделать get role
Или здесь отлавливать IOE

2024-11-17 15:03 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                opt => opt.AddRequirements(new PermissionTypeRequirement(permissionType)));
Скорее всего такая политика должна также поддерживать .AddRequirements(new UserExistsRequirementMarker())
И .AddAuthenticationSchemes([Auth.AuthProviders.GOOGLE, Auth.AuthProviders.YANDEX]))
Т.е. иметь все те же требования, что и Default Policy + Доп требования на permission

2024-11-17 15:04 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                opt => opt.AddRequirements(new PermissionTypeRequirement(permissionType)));
И там как раз UserExist в конвеере установит нужный клейм. Который можно будет через фасад получить

2024-11-17 15:06 UTC, AlexBimlnk commented on BookHub.Logic/Services/Account/RolesService.cs
> +    public async Task<Role?> GetUserRoleAsync(Id<User> userId, CancellationToken token)
убери nullable и catch

2024-11-17 15:06 UTC, AlexBimlnk commented on BookHub.Logic/Services/Account/RolesService.cs
> +        _logger.LogInformation("Adding new role {Name}", role.Name.Value);
debug

2024-11-17 15:06 UTC, AlexBimlnk commented on BookHub.Logic/Services/Account/RolesService.cs
> +        _logger.LogInformation("Changing permissions for role {Name}", updatedRole.Name.Value);
debug

2024-11-17 15:06 UTC, AlexBimlnk commented on BookHub.Logic/Services/Account/RolesService.cs
> +        _logger.LogInformation(
debug

2024-11-17 15:09 UTC, AlexBimlnk commented on BookHub.Models/Account/PermissionType.cs
> +
Не надо оверхедить. Мы вообще на встречу про один permission договорились.
Оставьте два разрешения - модерация контента и модерация пользователей. (второе будет использоваться для изменения роли/разрешений). @wi1sp @Tigeroff2002

2024-11-17 15:09 UTC, AlexBimlnk commented on BookHub.Models/Account/Role.cs
> +    public Role(
Все еще нет id

2024-11-17 15:10 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Abstractions/IRepositoryContext.cs
> +    public DbSet<Role> Roles { get; }
Тогда и там поменяй с UserRoles -> Roles. Или наоборот здесь поменяй

2024-11-17 15:11 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksHubContext.cs
> +    private static void CreateRole(ModelBuilder modelBuilder)
Навигационное свойство добавили. Но не описали. Опять.
HasMany users здесь должно быть.

2024-11-17 15:15 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                .SingleOrDefaultAsync(
x => x.Id == roleId

2024-11-17 15:16 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                    $"Role with name '{clarifiedRoleName.Value}' is not already exists.");
Role with id {roleId.Value} is not exists

2024-11-17 15:16 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                    $"User with id {userId.Value} not exists");
is not?

2024-11-17 16:10 UTC, wi1sp commented on BookHub.Models/Account/PermissionType.cs
> +
Да пускай будет, если Кирилл реализовал

2024-11-18 08:01 UTC, Tigeroff2002 commented on migrations/001_create_user.up.sql
> +INSERT INTO roles (name, claims) VALUES ('super_admin', '{"moderate_comments", "moderate_reviews", "create_topics", "change_book_visibility", "manage_user_actions", "manage_user_accounts", "change_us
Ладно, уберу супер

2024-11-18 08:52 UTC, Tigeroff2002 commented on BookHub.Models/Account/PermissionType.cs
> +
Уже сделано - что написано пером, то не вырубишь топором

2024-11-18 08:52 UTC, Tigeroff2002 commented on BookHub.Models/Account/Role.cs
> +    public Role(
И не будет

2024-11-18 08:54 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RolesRepository.cs
> +                    $"User with id {userId.Value} not exists");
does not вообще правильно - но я не буду править это

2024-11-18 08:58 UTC, Tigeroff2002 commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                opt => opt.AddRequirements(new PermissionTypeRequirement(permissionType)));
Слишком сложно - проще отдельным хэндлером - который может вызываться, а может и игноироваться

2024-11-18 09:44 UTC, wi1sp submitted a review, later dismissed

2024-11-18 13:09 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                opt => opt.AddRequirements(new PermissionTypeRequirement(permissionType)));
Суть такова: надо обязательно проверить, что эта политика не перекрывает default политику, а расширяет её, добавляя новые ограничения. Чтобы нельзя было без токена туда зайти

2024-11-18 13:09 UTC, AlexBimlnk commented on BookHub.Models/Account/Role.cs
> +    public Role(
Будет. В базе он есть. Отдавай на фронт вместе с id для выбора роли и не надо кучу костылей здесь воротить

2024-11-18 13:10 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksHubContext.cs
> +    private static void CreateRole(ModelBuilder modelBuilder)
Вы сами захотели всё это писать... Я изначально не был сторонником использования навигационных свойств

2024-11-18 14:05 UTC, AlexBimlnk requested changes
Временно чтобы не сливали без ревью

2024-11-18 21:15 UTC, AlexBimlnk commented
Вот теперь вроде работает

2024-11-18 21:17 UTC, AlexBimlnk approved these changes

2024-11-19 06:24 UTC, wi1sp approved these changes

2024-11-19 07:09 UTC, Tigeroff2002 commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +    public Task<IReadOnlyCollection<Role>> GetAllRolesAsync(CancellationToken token);
Айди не нужно было в доменной роли

2024-11-19 07:10 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/UsersRepository.cs
> +            RoleId = 1,
Нет смысла указывать здесь это

2024-11-19 07:11 UTC, merged

2024-11-19 08:14 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/UsersRepository.cs
> +            RoleId = 1,
Без этого НЕ РАБОТАЕТ

2024-11-19 08:15 UTC, AlexBimlnk commented on BookHub.Abstractions/Logic/Services/Account/IRolesService.cs
> +    public Task<IReadOnlyCollection<Role>> GetAllRolesAsync(CancellationToken token);
Нужно. И возвращать кортеж из модели и её айди это просто нечто. Это должно быть включено в её модель, также как и id любой другой сущности

2024-11-19 08:16 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/UsersRepository.cs
> +            RoleId = 1,
Подразумеваю потому, что ef трекает реляционные отношения (потому что мы их указываем).