#119 Add scoping support
book-hub-umsp/book-hub-api pull request #120
Opened 2024-11-20 18:51 UTC by AlexBimlnk

resolved #119

2024-11-20 19:21 UTC, wi1sp approved these changes

2024-11-21 08:30 UTC, Tigeroff2002 requested changes
Не совсем я понял прикола - почему у тебя скоп открывается только в Me методе контроллера?
Надо и в остальных тоже открыть тогда - так как там он же разрушаться будет и создаваться на каждый запрос новый

2024-11-21 15:48 UTC, AlexBimlnk commented
@Tigeroff2002 я просто тестил, что скоупы в логах выводятся. Вот. Я пока трассировку не планировал делать

2024-11-21 15:56 UTC, AlexBimlnk commented
И мы её наверное на каком нибудь middleware сделаем

2024-11-21 15:56 UTC, merged