feature/#121 Add domain and storage representation of book chapters with CRUD methods
book-hub-umsp/book-hub-api pull request #123
Opened 2024-11-25 08:22 UTC by Tigeroff2002

Добавил модели для глав книги на уровне домена и хранилища, миграции и методы репозиториев, выполняющих базовые операции над главами

По поводу размера глав - ничего здесь не учитывал, это надо будет после ресерча (которым вроде как не я занимаюсь) добавлять отдельной фичей

resolved #121

2024-11-25 17:10 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/ChapterPreview.cs
> +public sealed class ChapterPreview
не нужно превью

2024-11-25 17:12 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        PaginationBase pagination,
не нужна пагинация

2024-11-25 17:20 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +    {
Надо добавить ограничение на создание. Пусть будет не больше 5 глав на книгу.

2024-11-25 17:25 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/ChapterPreview.cs
> +public sealed class ChapterPreview
Можно в превью книги добавить список идентификаторов глав

2024-11-25 17:28 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +            .SingleOrDefaultAsync(x => x.Id == chapterId.Value, token);
почему не find?

2024-11-25 17:30 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/Chapter.cs
> +    public Name<Chapter> Title { get; }
Но в целом можно и chapter оставить так уж и быть

2024-11-25 17:42 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/Content.cs
> +    public Content(string value)
поставь ограничение на 40к символов.
Это будет +- <85кб текста и как раз не будет в loh улетать. Потестим насколько этого будет хватать для удобного использования

2024-11-25 19:31 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/Chapter.cs
> +    public Name<Chapter> Title { get; }
Том - очень неинтуитивно. Title может быть, а может и не быть (я сделал для него формат "Глава {Number}"

2024-11-25 19:31 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/ChapterPreview.cs
> +public sealed class ChapterPreview
Нужно. Ты делаешь запрос к книге - и тебе дается список превью глав
Ты нажимаешь на превью - и только тогда какой то контент будет грузиться

2024-11-25 19:33 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +            .SingleOrDefaultAsync(x => x.Id == chapterId.Value, token);
Тут везде Single. Я не особо разбираюсь, чем Find лучше

2024-11-25 19:37 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/Content.cs
> +    public Content(string value)
++

2024-11-25 19:56 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/Chapter.cs
> +    public Name<Chapter> Title { get; }
Хотя на уровне хранилища действительно можно и не хранить

2024-11-25 20:03 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/ChapterPreview.cs
> +public sealed class ChapterPreview
Нет, мы достанем первую книгу когда щелкнем по ней. Уже у нас есть превью, переходя на книгу у нас должна читаться первая глава. И мы их будем последовательно грузить по идее. Хотя даже не последовательно. Там будет просто конкретная доставаться. Поэтому для превью книги можно хранить список идентификаторов глав.

2024-11-25 20:03 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        PaginationBase pagination,
Да потому что это не главы.... Мы это делаем только из за особенностей хранения. Это куски большие книги. И их не будет много

2024-11-25 20:04 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +            .SingleOrDefaultAsync(x => x.Id == chapterId.Value, token);
find сначала в кэш смотрит, поэтому если есть вероятность того, что оно будет в кэше то лучше его использовать

2024-11-25 20:05 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +    {
Создал. Сделал проверки для добавления новых глав и самой модели номера
Ну и решил перерасчет номеров при удалении главы делать

2024-11-25 20:06 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +    {
Хотя в будущем, конечно, нужно бы предусмотреть возможность свапа номеров у глав - если автор решит последовательность сюжета поменять

2024-11-25 20:06 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/Chapter.cs
> +    public Name<Chapter> Title { get; }
Сделал только на доменном уровне чтоб было

2024-11-25 20:07 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        PaginationBase pagination,
Хотя если 5 глав - то ок, уберу

2024-11-25 20:19 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/ChapterPreview.cs
> +public sealed class ChapterPreview
Ну можно и так, конечно

2024-11-25 20:20 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +            .SingleOrDefaultAsync(x => x.Id == chapterId.Value, token);
++

2024-11-25 21:45 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/Chapter.cs
> +    public Name<Chapter> Title { get; }
тайтл надо убрать 120%

2024-11-25 21:46 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/ChapterTitle.cs
> +public sealed record class ChapterTitle
это не нужно от слова совсем
Если надо будет отобразить что то на фронте, фронты сами строчку соберут

2024-11-25 21:48 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        var restOfChapters =
тогда лучше сначала загрузить потом find делать

2024-11-25 21:50 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        var existedChapter = await Context.Chapters
надо и сказать что это "удаляемая глава"

2024-11-25 21:51 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +    public async Task<IReadOnlyCollection<ChapterNumber>> GetBooksChaptersNumbersAsync(
добавь в превью книги список id глав а это убери

2024-11-26 09:39 UTC, wi1sp commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Вопрос конечно насколько тут нужен именно такой способ хранения последовательности

2024-11-26 10:56 UTC, AlexBimlnk commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Big int точно не нужен. 
Можно вообще самый маленький тип выбрать

2024-11-26 11:47 UTC, Tigeroff2002 commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
smallint сделал

2024-11-26 12:06 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +    public async Task<IReadOnlyCollection<ChapterNumber>> GetBooksChaptersNumbersAsync(
++

2024-11-26 12:09 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        var restOfChapters =
ок

2024-11-26 12:09 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        var existedChapter = await Context.Chapters
ок

2024-11-26 12:20 UTC, wi1sp commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Если последовательность через отдельную таблицу сделать, то можно вообще все на триггерах бахнуть

2024-11-26 12:44 UTC, AlexBimlnk commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
А в чем смысл еще одну таблицу завозить? И какие триггеры?

2024-11-26 12:47 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/Content.cs
> +    public Content(string value)
@wi1sp вопрос к dba, там по идее около 16кб запись. Нужно инфа как это будет работать с т.з базы, ну т.е. понятно что там вроде линкед листа, но насколько это будет ощутимо?

2024-11-26 12:50 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        CreatingChapter chapter,
убери намбер для создаваемой модели, мы его сами проставим и валидировать ничего не надо будет

2024-11-26 12:52 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        var currentBookChapters = existedBook.Chapters.ToList();
А это зачем? У ICollection есть Count свойство. Перегонять в лист нужно

2024-11-26 12:56 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        foreach (var bookShortModel in booksShortModels)
Вернее в респон превью ты добавил. Теперь нужно в домен-превью добавить.

2024-11-26 12:57 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var booksChaptersNumbers = new Dictionary<long, IReadOnlyList<ChapterNumber>>();
Выше просто сделай include. А в Select выбери еще список. И не надо вот этого всего делать

2024-11-26 12:58 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/ChapterNumber.cs
> +    public static readonly int MAX_NUMBER = 5;
MIN тоже в константу

2024-11-26 12:59 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var booksChaptersNumbers = new Dictionary<long, IReadOnlyList<ChapterNumber>>();
Ну с include ты так не сделаешь, я пробовал

2024-11-26 12:59 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/Chapter.cs
> +public sealed class Chapter
Может тогда назвать это все Section?? Секция типа. Модель секции книги. Ну поотому что глава не матчится тоже по смыслу

2024-11-26 13:00 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Responses/Books/Repository/BookPreview.cs
> +    public required int[] ChaptersNumbers { get; init; }
ids

2024-11-26 13:00 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/CreatingChapter.cs
> +    public ChapterNumber ChapterNumber { get; }
Ну бля да, уже 10 раз бизнес требования поменялисб, уже теперь оно не надо

2024-11-26 13:00 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/ChapterNumber.cs
> +    public static readonly int MAX_NUMBER = 5;
Не вижу смысла, она не поменяется

2024-11-26 13:01 UTC, AlexBimlnk commented on BookHub.Models/Books/Repository/BookPreview.cs
> +    public IReadOnlyList<ChapterNumber> ChapterNumbers { get; }
Тут должен быть список идентификаторов. Иначе мы не достанем. Или пар id-number.

2024-11-26 13:01 UTC, Tigeroff2002 commented on BookHub.Contracts/REST/Responses/Books/Repository/BookPreview.cs
> +    public required int[] ChaptersNumbers { get; init; }
не говорит ни о чем

2024-11-26 13:02 UTC, Tigeroff2002 commented on BookHub.Models/Books/Repository/BookPreview.cs
> +    public IReadOnlyList<ChapterNumber> ChapterNumbers { get; }
А это не список?

2024-11-26 13:03 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var booksChaptersNumbers = new Dictionary<long, IReadOnlyList<ChapterNumber>>();
JOIN написать? Самим тогда? Я уверен что можно сделать. Я думаю можно самим linq join грамотный написать в таком случае

2024-11-26 13:03 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/CreatingChapter.cs
> +    public ChapterNumber ChapterNumber { get; }
Не нужно только при создании

2024-11-26 13:04 UTC, AlexBimlnk commented on BookHub.Models/Books/Content/ChapterNumber.cs
> +    public static readonly int MAX_NUMBER = 5;
такой подход, магические числа называется

2024-11-26 13:04 UTC, Tigeroff2002 commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Закрыл потому что ниже был еще комментарий. 
Я вообще не понимаю, зачем тут какой то оверинжиниринг. Какие то связные списки, тригеры - нахуя это надо
У нас все через приложение делается, мы не должны загоняться, что кто то через БД что то сломает нам

2024-11-26 13:22 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Responses/Books/Repository/BookPreview.cs
> +    public required int[] ChaptersNumbers { get; init; }
Говорит о многом, потому что идентификаторы глав и их порядковый номер не одно и тоже.
И давай лучше не number, а sequence_number назовем (порядковый номер)

2024-11-26 13:22 UTC, AlexBimlnk commented on BookHub.Models/Books/Repository/BookPreview.cs
> +    public IReadOnlyList<ChapterNumber> ChapterNumbers { get; }
Это список порядковых номеров, он ничего не даст нам.

2024-11-26 13:38 UTC, wi1sp commented on migrations/002_create_book.up.sql
Мне кажется можно не номера сделать
А типа связанный список

2024-11-26 13:41 UTC, wi1sp commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
> А в чем смысл еще одну таблицу завозить? И какие триггеры?

ну это уже просто пример что так можно

2024-11-26 13:43 UTC, wi1sp commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
> Закрыл потому что ниже был еще комментарий. Я вообще не понимаю, зачем тут какой то оверинжиниринг. Какие то связные списки, тригеры - нахуя это надо У нас все через приложение делается, мы не должны загоняться, что кто то через БД что то сломает нам

тригеры чтобы это база делала
ссылки чтобы с номерами не ебаться

2024-11-26 13:53 UTC, wi1sp commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Использования номеров в пре нигде не увидел
Соотвествено не вижу проблемы их убрать

2024-11-26 16:32 UTC, AlexBimlnk commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Их фронты по большей части будут использовать. Вообще это sequence number по хорошему

2024-11-26 20:11 UTC, wi1sp commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
Ну их можно сгенерить после загрузки из базы

2024-11-26 21:36 UTC, wi1sp requested changes
апрува не будет пока задачу не чекнешь
https://github.com/book-hub-umsp/book-hub-api/issues/76

2024-11-27 07:11 UTC, Tigeroff2002 commented
@wi1sp Ты прикалываешься? Я эту задачу смотрел, я даже комментарий в ней оставил

2024-11-27 07:15 UTC, Tigeroff2002 commented on migrations/002_create_book.up.sql
> +    number BIGINT NOT NULL,
> Использования номеров в пре нигде не увидел
> Соотвествено не вижу проблемы их убрать
А как тебе номеры должны использоваться? Номера в домене нужны для поддержания доменной целостности и упорядоченности
И как я на уровне БД вообще что то должен делать, если у меня таблица с главами - в которой идут не упорядоченно по разным книгам главы, айдишник их в БД просто для СУБД
Только и остается держать поле - и в домене при CRUD операции проверять его

2024-11-27 07:19 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var booksChaptersNumbers = new Dictionary<long, IReadOnlyList<ChapterNumber>>();
Я не знаю как, и не уверен что это будет работать

2024-11-27 07:32 UTC, Tigeroff2002 commented on BookHub.Models/Books/Content/CreatingChapter.cs
> +    public ChapterNumber ChapterNumber { get; }
кк

2024-11-27 07:32 UTC, Tigeroff2002 commented on BookHub.Contracts/REST/Responses/Books/Repository/BookPreview.cs
> +    public required int[] ChaptersNumbers { get; init; }
кк

2024-11-27 07:33 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/ChaptersRepository.cs
> +        var currentBookChapters = existedBook.Chapters.ToList();
кк

2024-11-27 08:16 UTC, wi1sp commented
> @wi1sp Ты прикалываешься? Я эту задачу смотрел, я даже комментарий в ней оставил
Нет, ты последние сообщения читал?

2024-11-27 10:37 UTC, wi1sp commented
> > Нет, ты последние сообщения читал?
> 
> Какие?

Хз

2024-11-27 10:39 UTC, wi1sp commented
> > Нет, ты последние сообщения читал?
> 
> Какие?

Хз

2024-11-27 15:09 UTC, wi1sp requested changes
Стил не посмотрел

2024-11-27 19:18 UTC, wi1sp approved these changes

2024-11-28 12:19 UTC, Tigeroff2002 commented
@wi1sp @AlexBimlnk жду какой то реакции уже

2024-11-28 12:31 UTC, AlexBimlnk approved these changes

2024-11-28 13:09 UTC, merged