Feature/#21 book models
book-hub-umsp/book-hub-api pull request #29
Opened 2024-10-17 17:24 UTC by Tigeroff2002

#21  resolved

Тесты не вижу смысла добавлять на эти модели

2024-10-18 15:22 UTC, AlexBimlnk commented on BookHub.Models/Books/Book.cs
> +    public BookText Text
В этой задаче мы описываем контейнер, "репоизторий" для книги. Контент будет в других задачах реализовываться
Или что это, непонятно

2024-10-18 15:24 UTC, AlexBimlnk commented on BookHub.Models/Books/BookAuthor.cs
> +    public Id<User> AuthorId { get; }
приставку author бы убрать, так как book author говорит за себя. 
И вообще зачем это все? Можно просто в книге держать AuthorId (Id<User>) и этого будет достаточно, разве нет?

2024-10-18 15:25 UTC, AlexBimlnk commented on BookHub.Models/Books/BookDefinition.cs
> +    public Name<Book> Caption { get; private set; }
Title?

2024-10-18 15:26 UTC, AlexBimlnk commented on BookHub.Models/Books/BookBriefDescription.cs
> +public sealed record class BookBriefDescription
BookAnnotation?

2024-10-18 15:26 UTC, AlexBimlnk commented on BookHub.Models/Books/BookDefinition.cs
> +public sealed class BookDefinition
BookDescription?

2024-10-18 15:28 UTC, AlexBimlnk commented on BookHub.Models/Books/BookDefinition.cs
> +        ArgumentNullException.ThrowIfNull(nameof(newCaption));
а вот были бы тесты, понял бы, что это не работает. 
На логику тесты желательно писать!

И вообще, пока не очень понятна модель изменений, я бы лучше логику накручивал в отдельных задачах. Сейчас пока просто контейнеры с данными создадим.

2024-10-18 15:30 UTC, AlexBimlnk commented on BookHub.Models/Books/BookGenre.cs
> +public enum BookGenre
Круто) 
Может добавить "эссе" еще?

2024-10-18 15:32 UTC, AlexBimlnk commented on BookHub.Models/Books/BookStatus.cs
> +    Removed
Deleted?

2024-10-18 15:33 UTC, AlexBimlnk commented on BookHub.Models/Books/BookText.cs
> +public sealed record class BookText
Это все в отдельных задачх будем думать над контентом.
Здесь только контейнер для книги, её репозиторий, верхнеуровневое описание

2024-10-18 15:35 UTC, AlexBimlnk commented on BookHub.Models/Books/BooksGenreResolver.cs
> +    private static readonly FrozenDictionary<BookGenre, string> _russianResolvers =
локали нужно отдельным компонентов поставлять, а лучше вообще какие то бест практис почитать. И сейчас пока этого не делать. 
Лучше создай ишус на локализацию, и ссылку туда эту закинь. А как руки дойдут, то возьмем. А здесь пока это не нужно

2024-10-18 15:35 UTC, AlexBimlnk commented on BookHub.Models/Books/KeyWord.cs
> +/// Ключевое словосочетание.
просто **слово** же

2024-10-18 15:35 UTC, AlexBimlnk commented on BookHub.Models/Books/KeyWord.cs
> +    private const int MAX_LENGHT = 250;
кажется слишком много для ключевого слова

2024-10-18 15:36 UTC, AlexBimlnk commented on BookHub.Models/Common/UserFavourite.cs
> +/// Избранное из книг у пользователя.
Так, на это уже другая задача есть (#23), не надо реализовывать то, что в задаче не требовалось и будет вообще другими делаться

2024-10-18 15:37 UTC, AlexBimlnk commented on BookHub.Models/Common/UserFavouriteBookLink.cs
> +public sealed class UserFavouriteBookLink : IEquatable<UserFavouriteBookLink>
аналогично

2024-10-18 15:38 UTC, AlexBimlnk commented on BookHub.Models/Books/Book.cs
> +public sealed class Book
у книги явно тоже id есть

2024-10-18 15:38 UTC, AlexBimlnk commented on BookHub.Logic/Configuration/BookTextConfiguration.cs
> +public sealed class BookTextConfiguration
не нужно

2024-10-18 15:38 UTC, AlexBimlnk commented on BookHub.Logic/Configuration/BookTextConfigurationValidator.cs
> +public sealed partial class BookTextConfigurationValidator
не нужно

2024-10-18 15:40 UTC, AlexBimlnk requested changes
в задаче было сказано добавить только модели верхнеуровнего описания книги. Убери пожалуйста все что не нужно здесь

2024-10-20 12:29 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookAuthor.cs
> +    public Id<User> AuthorId { get; }
Ок

2024-10-20 12:31 UTC, Tigeroff2002 commented on BookHub.Models/Books/Book.cs
> +    public BookText Text
Это модель дял текста - чтобы он отдельно настраивался и валидировался по длине на этапе сбора книги

2024-10-20 12:32 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookDefinition.cs
> +    public Name<Book> Caption { get; private set; }
ок

2024-10-20 12:36 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookDefinition.cs
> +public sealed class BookDefinition
+

2024-10-20 12:36 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookDefinition.cs
> +        ArgumentNullException.ThrowIfNull(nameof(newCaption));
поправлю. логику не хочу отдельно заводить - потому что и не логика, а просто обертка над приватным сеттером

2024-10-20 12:38 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookGenre.cs
> +public enum BookGenre
Добавлю

2024-10-20 12:39 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookGenreGroup.cs
> +public enum BookGenreGroup
убрал енам этот пока

2024-10-20 12:39 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookStatus.cs
> +    Removed
Removed кажется более точно описывает

2024-10-20 12:43 UTC, Tigeroff2002 commented on BookHub.Models/Books/KeyWord.cs
> +    private const int MAX_LENGHT = 250;
Уменьшу до 20

2024-10-20 12:43 UTC, Tigeroff2002 commented on BookHub.Models/Books/KeyWord.cs
> +/// Ключевое словосочетание.
+

2024-10-20 12:43 UTC, Tigeroff2002 commented on BookHub.Models/Common/UserFavourite.cs
> +/// Избранное из книг у пользователя.
Будет ли оно кем то делаться - это конечно вопрос

2024-10-20 12:45 UTC, Tigeroff2002 commented on BookHub.Models/Common/UserFavourite.cs
> +/// Избранное из книг у пользователя.
Но я там закинул в текст задачи это, чтобы не пропадало

2024-10-20 12:45 UTC, Tigeroff2002 commented on BookHub.Models/Common/UserFavouriteBookLink.cs
> +public sealed class UserFavouriteBookLink : IEquatable<UserFavouriteBookLink>
+

2024-10-20 12:46 UTC, Tigeroff2002 commented on BookHub.Models/Books/Book.cs
> +public sealed class Book
+

2024-10-20 12:47 UTC, Tigeroff2002 commented on BookHub.Logic/Configuration/BookTextConfiguration.cs
> +public sealed class BookTextConfiguration
Ладно уберу это впринципе, больше вряд ли будем это регулировать как то, кажется бесмысленным

2024-10-20 12:48 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookText.cs
> +public sealed record class BookText
Пусть пока повисит в этом виде, хотя бы просто как декоратор строчки. Потом уже можно в отдельной задаче что то с ним сделать

2024-10-21 11:15 UTC, WillzzArt approved these changes

2024-10-21 14:56 UTC, AlexBimlnk commented on BookHub.Models/Books/BookAnnotation.cs
> +public sealed record class BookAnnotation
Я бы на самом деле не стал делать аннотацию обязательной к книге, но пока оставим а дальше если че сообразим

2024-10-21 14:58 UTC, AlexBimlnk approved these changes

2024-10-22 07:25 UTC, merged

2024-10-22 21:01 UTC, AlexBimlnk commented
@Tigeroff2002 теги версий нужно ставить для версионирования!
И ишусы линкуй пожалуйста, чтобы они автоматически переводились в закрытое состояние