Feature/#22 books storage
book-hub-umsp/book-hub-api pull request #32
Opened 2024-10-22 08:09 UTC by Tigeroff2002

Добавил модели хранилища, контекст хранилища, репозитории с примерными методами и единицу работы для их использования
Возможно, сюда стоит добавить и миграцию сразу и подумать с devops team как их накатывать автоматом

2024-10-22 20:26 UTC, AlexBimlnk commented on BookHub.API/appsettings.json
>      "BookSymbolsMaxLimit": 10000000
это удалить надо

2024-10-22 20:28 UTC, AlexBimlnk commented on BookHub.Storage/Migrations/20241022081042_init books_db.cs
у нас классические миграции, не ef'овские.
А чтобы тестировать они тоже не нужно. Достаточно сделать context.EnsureCreated/Deleted

2024-10-22 20:29 UTC, AlexBimlnk commented on BookHub.Storage/Migrations/BooksContextModelSnapshot.cs
> +    partial class BooksContextModelSnapshot : ModelSnapshot
сделай нормальный контекст настраиваемый и без лишнего мусора

2024-10-22 20:32 UTC, AlexBimlnk commented on BookHub.Models/Books/KeyWord.cs
> +public sealed class KeyWord
Я не думаю, что ключевые слова должна задаваться строго определенным набором всё-таки. Это тяжело поддерживать, да и не нужно наверное. И вообще мы думали о том, чтобы их "генерировать" для книги.
Связь с книгой создать - да, нужно.
Если так и предполагается - то ок.

Но в таком случае странно видеть Name модель здесь. Я бы от нее ушел, оставил string. И Content -> Value

2024-10-22 20:32 UTC, AlexBimlnk commented on BookHub.Models/Books/KeyWord.cs
> +public sealed class KeyWord
И record оставить желательно

2024-10-22 20:35 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Abstractions/Repositories/IAuthorsRepository.cs
> +public interface IAuthorsRepository
К сожалению здесь почти все придется переписать. И никто не просил делать реализацию хранилища авторов..
Еще раз - мы описываем книгу. Только книгу. У нее есть ссылка на автора, и не более того. Не нужно ничего вкручивать, когда очевидно нет еще достаточных сущностей и контекста, чтобы это все вкручивать - по факту просто потраченное впустую время.
Никто не будет автора по имени добавлять, никто не будет имя автора по айди доставать.

2024-10-22 20:37 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksContext.cs
> +    public DbSet<Author> Authors { get; } = null!;
рекомендую убрать все, что связано с "авторами" в данном пул реквесте, потому что это так работать просто напросто не будет. У нас User и автор идентичны по факту. Это надо позже думать

2024-10-22 20:37 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksContext.cs
> +    public DbSet<Author> Authors { get; } = null!;
Кроме естественно просто ссылки. И скорее всего ссылки в виде Id<User>

2024-10-22 20:40 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Models/KeyWord.cs
> +    public required string Content { get; set; }
required убери
И лучше все же Value назвать кмк

2024-10-22 20:41 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Models/KeyWordLink.cs
> +/// Ссылки на ключевые слова.
Связь между ключевым словом и книгой

2024-10-22 20:42 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Models/KeyWord.cs
> +/// Ключевое слов.
словО

2024-10-22 20:42 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/AuthorsRepository.cs
> +public sealed class AuthorsRepository :
не нужно

2024-10-22 20:44 UTC, AlexBimlnk commented on Migrations/init_db.sql
> +CREATE TABLE authors (
не нужно

2024-10-22 20:44 UTC, AlexBimlnk commented on Migrations/init_db.sql
Это разве с DBA не нужно синкать??
Я кстати за то, чтобы база называлась bookhub_db, так как она одна и не только для книг
@wi1sp FYI

2024-10-22 20:45 UTC, AlexBimlnk commented on Migrations/init_db.sql
В общем я за то, чтобы миграция заезжали отдельно с апрува DBA

2024-10-22 20:46 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/UnitOfWorkFactory.cs
> +        var scope = _scopeFactory.CreateScope();
как его диспоузить?

2024-10-22 20:47 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RepositoriesBase.cs
> +public abstract class RepositoriesBase
**Repository**Base

2024-10-22 20:51 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/KeyWordsRepository.cs
> +        await Context.SaveChangesAsync(token);
я понимаю, что приходится делать для того, чтобы сущность обзавелась id, но это выбивается из общего пайплайна работы. И сейчас не видно причин все это делать, нет причин для того, чтобы возвращать этот id.
И вообще кейворд наверняка может добавляться в базу только вместе с отношением к книге. Т.е. здесь нужен book id

2024-10-22 20:52 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +            storageBook.KeywordsLinks =
контекст вообще с множествами нормально работает?? Я вот что-то не уверен. И лучше делать на хранилище ICollection интерфейсы канонические, а сеты уже на уровне домена

2024-10-22 20:53 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/RepositoryContext.cs
> +    public async Task SaveChangesAsync(CancellationToken token)
пока не нужно

2024-10-22 20:54 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +                await Context.Books
то переносишь, то не переносишь, хоть бы в едином стиле писал

2024-10-22 20:55 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        catch (InvalidOperationException)
это сильно конечно.
Просто верну SingleOrDefault и если null - кинь эксепшен, зачем вот эти все трай кечи городить с выбросом новых ошибок??????

2024-10-22 20:56 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        catch
не надо  так делать......

2024-10-22 20:56 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        catch
откуда вообще такая мысль задизайнить появилась я даже не представляю, шок

2024-10-22 20:57 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksUnitOfWork.cs
> +    public BooksContext Context { get; }
не используется нигде. Не нужно это проперти

2024-10-22 20:59 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Abstractions/IBooksUnitOfWork.cs
Надо кстати понимать, что абстракции репозиториев и единиц работы нужно поместить не в проекте с реализацией хранилища. А в отдельном проекте Abstractions
Иначе Logic будет зависить от Storage, а это неверно, нарушение принципа инверсии зависимостей. Это Storage должен зависить от абстракций верхнего уровня

2024-10-22 21:00 UTC, AlexBimlnk requested changes
убери ef миграции, все что связано с авторами и адские костыли. Добавь проект abstractions и вынеси туда абстракции, которые будет использовать слой логики, а реализовывать - слой хранилища.

2024-10-22 21:02 UTC, AlexBimlnk commented
И добавь всю методату к ПР - проект, метки и ишус

2024-10-23 10:35 UTC, Tigeroff2002 commented
Капец ты душный чел

2024-10-23 13:15 UTC, wi1sp commented on Migrations/init_db.sql
> +CREATE TYPE book_genre as ENUM (
Я вообще не фанат enum -ов. Если со статусом ещё ок, но я бы табличку отдельную сделал. То вот с жанрами 100℅ лучше табличку сделать.

2024-10-23 13:15 UTC, wi1sp commented on Migrations/init_db.sql
Мне диаграмму нарисовать надо?

2024-10-23 17:20 UTC, AlexBimlnk commented on Migrations/init_db.sql
> +CREATE TYPE book_genre as ENUM (
Надо наверное иметь в виду, что скорее всего можно несколько жанров у книги указать. Но на статус таблица выглядит излишней.

2024-10-23 17:21 UTC, AlexBimlnk commented on Migrations/init_db.sql
вообще наверное так или иначе структуру хранилища лучше куда нибудь занести энивей.

2024-10-24 09:21 UTC, Tigeroff2002 commented on Migrations/init_db.sql
> +CREATE TYPE book_genre as ENUM (
Заводить таблицу в данном случае - это перебор. Куча логики еще к тому же и ограничений сразу появится
Это нормальная практика. А если надо будет подредактировать тип енама - то просто делается миграция
Я не буду делать табличек в общем. По поводу схем данных - не ты явно должен ее чертить

вот тебе схема
![image](https://github.com/user-attachments/assets/4d56404d-8182-4deb-a272-e34d38734e1f)

2024-10-24 09:22 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Abstractions/IBooksUnitOfWork.cs
Я не буду тут задрачиваться по поводу чистой архитектуры

2024-10-24 09:23 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        catch (InvalidOperationException)
мне так нравится, так меньше ифов

2024-10-24 09:23 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +                await Context.Books
не принципиально

2024-10-24 09:23 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/RepositoryContext.cs
> +    public async Task SaveChangesAsync(CancellationToken token)
Нужно, иначе бы я не добавлял

2024-10-24 09:24 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +            storageBook.KeywordsLinks =
Ну соберет, ничего страшного

2024-10-24 09:25 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/KeyWordsRepository.cs
> +        await Context.SaveChangesAsync(token);
Нет. Ключевое слово - это набор уже сгенерированных тэгов. Которые можно к книге прилинковать - то есть они уже должны быть созданы
А айди должен при создании возвращаться на фронт - чтобы юзер сразу мог видеть и использовать свои изменения

2024-10-24 09:26 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/UnitOfWorkFactory.cs
> +        var scope = _scopeFactory.CreateScope();
Не думаю, что здесь это сильно по памяти повлияет, так что пофиг

2024-10-24 09:26 UTC, Tigeroff2002 commented on Migrations/init_db.sql
структура хранилища есть как миграция (файл в ПРе) и где то я кинул еще и ER. Это надо после мержа занести в местный гугл диск

2024-10-24 09:26 UTC, Tigeroff2002 commented on Migrations/init_db.sql
> +CREATE TABLE authors (
нужно

2024-10-24 09:27 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/AuthorsRepository.cs
> +public sealed class AuthorsRepository :
нужно

2024-10-24 09:27 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Models/KeyWordLink.cs
> +/// Ссылки на ключевые слова.
и так понятно

2024-10-24 09:27 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Models/KeyWord.cs
> +    public required string Content { get; set; }
value слишком обще слово

2024-10-24 09:28 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/BooksContext.cs
> +    public DbSet<Author> Authors { get; } = null!;
Я не хочу ничего убирать связанного с авторами. Я делаю контекст книг (и в них должна быть сущность авторов)
То, что это будут те же юзеры потом - это не моя проблема. Ты придумаешь, как это прилинковать к аккаунт контексту - или я, если этим буду заниматься

2024-10-24 09:30 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Abstractions/Repositories/IAuthorsRepository.cs
> +public interface IAuthorsRepository
Фронт может искать имя по айди. И это просто минимальный контент пока - потом что угодно можно искать по автору, этот метод, как примерный образец, по пайплайну подходит.
Есть список книг - у каждой книги есть автор (автор айди) - и переходя к отдельной книге мы подгрузим имя автора и какую то инфу

2024-10-24 09:32 UTC, Tigeroff2002 commented on BookHub.Storage/Migrations/BooksContextModelSnapshot.cs
> +    partial class BooksContextModelSnapshot : ModelSnapshot
Файлы с миграциями пусть будут. Я потом хочу внося изменения в контекст видеть изменение в миграции - и соответственно пользоваться генерацией новой миграции от ef

2024-10-24 09:33 UTC, Tigeroff2002 commented on BookHub.Storage/Migrations/20241022081042_init books_db.cs
У кого, у нас? У тебя может быть что угодно, а я, как имплементатор, хочу сделать так. Никакие правила, как нужно, не закреплены, этот подход тоже распространен

2024-10-24 09:33 UTC, Tigeroff2002 commented on BookHub.API/appsettings.json
>      "BookSymbolsMaxLimit": 10000000
ок

2024-10-24 15:09 UTC, AlexBimlnk commented on BookHub.Models/Books/KeyWord.cs
> +public sealed class KeyWord
Как потом эти теги поддерживать? Это вообще дискуссионный вопрос где еще аналитики нужны и совместное решение.
Жанры мы выбираем, это ок еще. А тегов может быть очень-очень много, и добавлять их и ограничивать лично мне не хочется. На ютубе кстати ключевые слова тоже пользовательские. А поскольку это строки, то уникальность им не сложно гарантировать. Тем более что у тебя вообще там HashSet'ы использовались, ты их как без record применять то собрался?-

2024-10-24 15:10 UTC, AlexBimlnk commented on BookHub.Storage/Migrations/20241022081042_init books_db.cs
У нас это значит был звонок еще в начале и лично ты тоже говорил про написание sql руками, а не миграции через orm.

2024-10-24 15:11 UTC, AlexBimlnk commented on BookHub.Storage/Migrations/BooksContextModelSnapshot.cs
> +    partial class BooksContextModelSnapshot : ModelSnapshot
как "пользоваться"?

2024-10-24 15:12 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Abstractions/Repositories/IAuthorsRepository.cs
> +public interface IAuthorsRepository
Ты понимаешь что у нас в системе пользователь и автор идентичны?? 
Не надо делать больше в задаче, чем нужно, говорил много раз. И я не знаю зачем искать имя по айди.

2024-10-24 15:13 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksContext.cs
> +    public DbSet<Author> Authors { get; } = null!;
В твоем контексте достаточно держать условный ключ-ссылку на автора и не более того. Домен авторов/пользователей уже другая область

2024-10-24 15:16 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Models/KeyWordLink.cs
> +/// Ссылки на ключевые слова.
Какие "ссылки", на "ключевые слова"? Непонятно как раз
И лучше так и назвать KeyWordBookLink
А еще лучше удалить это вообще, потому как будут работать ключевые слова мы еще не знаем

2024-10-24 15:17 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/AuthorsRepository.cs
> +public sealed class AuthorsRepository :
я как автор задачи говорю что это НЕ НУЖНО
мы описываем книгу и то верхнеуровнего. Название, жанр, аннотация, дата создания. Id автора. Всё

2024-10-24 15:18 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/UnitOfWorkFactory.cs
> +        var scope = _scopeFactory.CreateScope();
не пофиг у тебя мемори лик может быть

2024-10-24 15:18 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/UnitOfWorkFactory.cs
> +        var scope = _scopeFactory.CreateScope();
И зачем вообще здесь фабрика нужна??

2024-10-24 15:21 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/KeyWordsRepository.cs
> +        await Context.SaveChangesAsync(token);
Вот ты это откуда взял? У нас нет никакого описания что такое ключевое слово. Может это список слов(словосочетаний), который пользователь сам задаст. Потому что иначе должен быть мейтаненс. А мейнтейнить тупо некому. И их овер много вообще может существовать. Но как я уже ранее написал, это вообще дискуссионный вопрос.

Не решают бизнес логику проекта на пул реквестах и что и как будет. Что фронт будет доставать а что не будет.
Я создал задачи на минимальное описание сущностней, которые сейчас очевидны.

2024-10-24 15:23 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/KeyWordsRepository.cs
> +        await Context.SaveChangesAsync(token);
И в твоем понимании что, юзер будет теги в базу заносить?? Это будет делать не юзер, а модератор, если вообще будет. А это в целом уже другой скоуп работ и пайплайн, его сейчас не нужно имплементировать, потому что мы НЕ ЗНАЕМ КАК.

2024-10-24 15:24 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/RepositoryContext.cs
> +    public async Task SaveChangesAsync(CancellationToken token)
Для чего оно нужно? Для возврата id ключевого слова, что к задаче совсем не относится.

2024-10-24 15:25 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        catch (InvalidOperationException)
Что? Каких ифов, ты эксепшен перехватил чтобы снова его выбросить. ЗАЧЕМ?

2024-10-24 15:25 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksUnitOfWork.cs
> +    public BooksContext Context { get; }
потом и добавим, если нужно будет

2024-10-24 15:26 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Abstractions/IBooksUnitOfWork.cs
А я буду. Я не хочу здесь говнокодить. Тем более по проекту который сам предложил.

2024-10-24 15:27 UTC, AlexBimlnk commented
@Tigeroff2002 Смайлик дизлайка на коменте я видел
Но может быть @wi1sp объяснит для чего нужно описывать методанные к пул-реквестам...

2024-10-24 15:33 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        await Context.SaveChangesAsync(token);
В таком подходе есть риск того, что у нас будет рваный стейт, я не представляю как его использовать вместе с паттерном UOW.

2024-10-25 06:20 UTC, Tigeroff2002 commented on BookHub.Storage/Migrations/20241022081042_init books_db.cs
Так он и будет писаться руками - это нужно для того чтобы девопсы бд организовывали на окружениях хотя бы
А на прикладном уровне я буду делать как хочу

2024-10-25 06:20 UTC, Tigeroff2002 commented on BookHub.Storage/Migrations/BooksContextModelSnapshot.cs
> +    partial class BooksContextModelSnapshot : ModelSnapshot
add-migration
update-database

2024-10-25 06:22 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Abstractions/Repositories/IAuthorsRepository.cs
> +public interface IAuthorsRepository
Я вообще мало чего тут понимаю. Я бы уже сделал, чтобы и пользователи и авторы работали нормально - в одной таблице.
Сейчас добавляются авторы в таком виде. Потом к ним линкуется новая таблица ProfileInfo с данными аккаунта. Или прямо в таблице authors

2024-10-25 06:22 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/BooksContext.cs
> +    public DbSet<Author> Authors { get; } = null!;
Которую такими темпами никогда не удасться получить

2024-10-25 06:23 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/AuthorsRepository.cs
> +public sealed class AuthorsRepository :
Я могу закрыть эту задачу как non_needed, завести свою, и сделать ее как хочу тогда

2024-10-25 06:24 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        catch (InvalidOperationException)
Этого уже нет, дядя

2024-10-25 06:25 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/BooksUnitOfWork.cs
> +    public BooksContext Context { get; }
Потом, потом, только и слышу. Потом уже проект закроется

2024-10-25 09:52 UTC, AlexBimlnk commented on BookHub.Storage/Migrations/20241022081042_init books_db.cs
Окей, а комитить в общих реп твои локальные решения то зачем?

2024-10-25 09:54 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Abstractions/Repositories/IAuthorsRepository.cs
> +public interface IAuthorsRepository
Поэтому и нужно делать все по чуть-чуть. То к чему есть понимание. Потому что сейчас у нас многое не устаканено и непонятно. Сделай просто понятие книга. И ключ на автора. И больше ничего не надо

2024-10-25 09:54 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksContext.cs
> +    public DbSet<Author> Authors { get; } = null!;
В смысле? У тебя же есть в сторожевой модели long AuthorId. Вот его и достаточно, больше ничего не надо.

2024-10-25 09:58 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/AuthorsRepository.cs
> +public sealed class AuthorsRepository :
Эта задачу "нужна". И что значит "делать как хочу"?? У нас проект на команду
Я просто прошу убрать то, что не относится к задаче, оставить только модель книги. И всё. Больше ничего не надо, потому что ничего еще не обсуждалось и непонятно. Нужны документы, работа аналитиков и договоренности на встречах что чего и как.

2024-10-25 10:01 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/BooksUnitOfWork.cs
> +    public BooksContext Context { get; }
Да, потом. Потому что времени на него немного и ничего не известно. Накручивать то, что потом удалять и переделывать нет смысла.
Да и какая разница закроется или нет.

2024-10-28 07:26 UTC, Tigeroff2002 commented on BookHub.Storage/Migrations/20241022081042_init books_db.cs
Убрал

2024-10-28 07:39 UTC, wi1sp requested changes

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
> +CREATE TYPE book_genre as ENUM (
enum убрать на таблицу

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
> +    author_id bigint NOT NULL DEFAULT 0,
почему дефолт 0 мб `NULL`

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
> +    author_id bigint NOT NULL DEFAULT 0,
либо вообще убрать дефолт

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
> +    book_annotation text NOT NULL,
annotaion имхо странное название мб description или синопсис но на английсокм

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
> +    creation_date timestamp with time zone NOT NULL,
дефолт `NOW()`?

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
Добавить опцию перезапускать миграцию и сделать её в одной транзакции

2024-10-28 07:39 UTC, wi1sp commented on Migrations/0_init_db.sql
> +    keywords_content json DEFAULT NULL,
`array`?

2024-10-28 07:57 UTC, AlexBimlnk requested changes

2024-10-28 07:57 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +    public async Task AddKeyWordsForBookAsync(
Update

2024-10-28 08:04 UTC, wi1sp requested changes

2024-10-28 08:04 UTC, wi1sp commented on Migrations/0_init_db.sql
разбить на отдельные миграции созданние бд и создание таблиц

2024-10-29 09:59 UTC, AlexBimlnk approved these changes

2024-10-29 11:36 UTC, WillzzArt approved these changes

2024-10-29 13:02 UTC, merged