Feature/#23 book fav models
book-hub-umsp/book-hub-api pull request #36
Opened 2024-10-27 17:45 UTC by WillzzArt

Добавлены модели для избранного

2024-10-27 17:59 UTC, AlexBimlnk requested changes

2024-10-27 17:59 UTC, AlexBimlnk commented on BookHub.Models/UserFavoriteBookLink.cs
> +public sealed class UserFavoriteBookLink
Убери время добавления, так как оно не нужно. Убери переопределение равенства и используй record

2024-10-27 17:59 UTC, AlexBimlnk commented on BookHub.Models/Favorite.cs
> +    public void ChangeLinks(IReadOnlySet<UserFavoriteBookLink> links) => AddLinks(UserId, links);
Убери всю логику пока что с моделей. Оставь просто контейнеры с данными

2024-10-27 17:59 UTC, AlexBimlnk commented on BookHub.Models/Favorite.cs
> +public sealed class Favorite
UserFavorits?

2024-10-29 08:55 UTC, Tigeroff2002 commented on BookHub.Models/UserFavoriteBookLink.cs
> +
убери пустую строчку
и кажется все таки стоило оставить время

2024-10-29 08:55 UTC, Tigeroff2002 commented on BookHub.Models/UsersFavorite.cs
> +        //AddLinks(userId, links);
Ты кажется убрал проверку на null для links

2024-10-29 10:00 UTC, AlexBimlnk commented on BookHub.Models/UserFavoriteBookLink.cs
> +
Зачем там время вообще, какая разница когда именно было добавлено в избранное??

2024-10-29 10:02 UTC, AlexBimlnk commented on BookHub.Models/UsersFavorite.cs
> +        IReadOnlySet<UserFavoriteBookLink> links)
а присваивание сделать??

2024-10-29 10:02 UTC, AlexBimlnk requested changes
.

2024-10-29 10:03 UTC, AlexBimlnk commented on BookHub.Models/UsersFavorite.cs
> +public sealed class UsersFavorite
UserFavorite

2024-10-29 19:14 UTC, AlexBimlnk submitted a review, later dismissed

2024-10-29 20:01 UTC, AlexBimlnk requested changes
просто фиксани названия и всё будет ок

2024-10-29 20:01 UTC, AlexBimlnk commented on BookHub.Models.Tests/UserFavoriteBookLink.Tests.cs
> +    [Fact(DisplayName = "Cannot create without name.")]
without book id

2024-10-29 20:01 UTC, AlexBimlnk commented on BookHub.Models.Tests/UsersFavorite.Tests.cs
> +    [Fact(DisplayName = "Cannot create without name.")]
without links

2024-10-30 07:54 UTC, Tigeroff2002 approved these changes

2024-10-30 08:09 UTC, merged