Feature/#27 book repos controller
book-hub-umsp/book-hub-api pull request #41
Opened 2024-10-30 13:03 UTC by Tigeroff2002

Добавил тут модели запросов, ответов для контроллера, занимающегося работой с верхне уровневым описанием книги
Для работы использовал сервис

Также немного подредактировал репозиторий книги - сделал единый метод обновления с выбором конкретных параметров того, что было изменено

#27 resolved

2024-10-30 13:03 UTC, Tigeroff2002 commented
Возможно, стоит еще добавить сюда метод контроллера и репозитория на получение всех жанров (и добавление нового жанра) - так как информация о них закрыта от фронта сейчас

2024-10-30 15:44 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookTopLevelDescriptionController.cs
> +public class BookTopLevelDescriptionController : Controller
BookDescriptionController

2024-10-30 15:46 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookTopLevelDescriptionController.cs
> +    [Route("/getBook")]
get

2024-10-30 15:49 UTC, AlexBimlnk commented on BookHub.Contracts/CommandConverter.cs
> +            CommandType.add_book => tokenizedRawCommand.ToObject<AddBookParams>(),
зачем нам эти типы команд вообще сейчас? у нас rest http api по нему итак понятно что именно за тип команды пришел. Есть put/post/delete. Зачем накручивать то, что не не требуется

2024-10-30 15:51 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/ScopedBookTopLevelDescriptionService.cs
> +        IServiceScopeFactory scopeFactory)
сделай его scoped и всё

2024-10-30 15:53 UTC, AlexBimlnk commented on BookHub.Models/Books/Book.cs
> +        private set => LastEditDate = DateTimeOffset.UtcNow;
это неправда. Так мы будем обновлять дату редактирования, даже когда самого редактирования не случилось

2024-10-30 15:54 UTC, AlexBimlnk commented on BookHub.Models/CRUDS/CommandResult.cs
> +public enum CommandResult
давай пока без вот этого вот всего обойдемся, это лишнее усложнение и проксирование, которое не нужно в сихронной модели с крудами

2024-10-31 07:16 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookTopLevelDescriptionController.cs
> +    [Route("/addBook")]
Можно убрать

2024-10-31 07:18 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookTopLevelDescriptionController.cs
> +public class BookTopLevelDescriptionController : Controller
++

2024-10-31 07:18 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookTopLevelDescriptionController.cs
> +    [Route("/getBook")]
++

2024-10-31 07:18 UTC, Tigeroff2002 commented on BookHub.Contracts/CommandConverter.cs
> +            CommandType.add_book => tokenizedRawCommand.ToObject<AddBookParams>(),
Думал, что нужно будет - пока можно убрать, роутинга апи хватает

2024-10-31 07:19 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/ScopedBookTopLevelDescriptionService.cs
> +        IServiceScopeFactory scopeFactory)
Кажется нужно - в АДФе зачем то это же делается

2024-10-31 07:21 UTC, Tigeroff2002 commented on BookHub.Models/Books/Book.cs
> +        private set => LastEditDate = DateTimeOffset.UtcNow;
Сделаю чуть по другому

2024-10-31 07:22 UTC, Tigeroff2002 commented on BookHub.Models/CRUDS/CommandResult.cs
> +public enum CommandResult
Это для доменной логики - сервис возвращает результат - и мы по этому енаму ориентируемся

2024-10-31 07:23 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var storageBook = addBookParams is AddAuthorBookParams authorBookParams
Так в любом случае нужно модель добавления с айди автора иметь. Ее фронт будет подставлять из куки - так что вот так оно примерно и будет работать

2024-10-31 09:05 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/ScopedBookTopLevelDescriptionService.cs
> +        IServiceScopeFactory scopeFactory)
Там это делается в BG сервисах потому что. А тут у тебя контроллеры.

2024-10-31 09:06 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var storageBook = addBookParams is AddAuthorBookParams authorBookParams
я к тому, чтобы создание книги - это создании книги конкретного пользователя. Его индивидуальное творчество, пока вот так

2024-10-31 09:08 UTC, AlexBimlnk commented on BookHub.Models/CRUDS/CommandResult.cs
> +public enum CommandResult
Ничего не понял, какой доменной логики. У тебя в контроллере уже есть разделение запросов get/post etc. И ты им возвращаешь нужный респонс просто моделей. Зачем еще эти "команды" городить непонятно от слова совсем.

2024-10-31 09:10 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [HttpPost]
put

2024-10-31 09:10 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [HttpPost]
get

2024-10-31 09:11 UTC, AlexBimlnk commented on BookHub.API/Program.cs
> +app.UseSwagger().UseSwaggerUI();
if (env is development)

2024-10-31 09:11 UTC, AlexBimlnk commented on BookHub.Contracts/CRUDS/Requests/AddBookParams.cs
> +    public IReadOnlyCollection<KeyWord> Keywords { get; set; } = null!;
init

2024-10-31 09:15 UTC, AlexBimlnk commented on BookHub.Logic/Converters/BookParamsConverter.cs
> +                new UpdateBookAnnotationParams(
почему не использовать мою унифицированную модель обновления? Чтобы не плодить кучу разных сущностей

2024-10-31 09:15 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +        catch (Exception ex)
стоит перехватывать только конкретные ожидаемые ошибки, а не любые

2024-10-31 09:16 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +
а сохранить??

2024-10-31 09:17 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +            _logger.LogInformation(
это debug, как и почти все логи здесь.

2024-10-31 09:18 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +        catch (Exception ex)
так может лучше в контроллере ошибки перехватывать и на основе них делать Ok/Bad и вот этим вот всем не заниматься. И модели команд не нужны будут, потому что у тебя эндпоинты возращают IActionResult<T> where T : ResponseModel

2024-10-31 09:19 UTC, AlexBimlnk commented on BookHub.Logic/CrudServices/ScopedBookDescriptionService.cs
> +public sealed class ScopedBookDescriptionService : IScopedBookDescriptionService
удалить

2024-10-31 09:20 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Models/Book.cs
> +    public long AuthorId { get; set; } = 0;
оставь как было

2024-10-31 09:21 UTC, AlexBimlnk commented on BookHub.Models/Books/BookDescription.cs
> +public sealed record class BookDescription
это не будет работать из-за HashSet

2024-10-31 09:23 UTC, AlexBimlnk commented on BookHub.Models/Books/Book.cs
> +        LastEditDate = DateTimeOffset.UtcNow;
так может управлять этим на уровне базы тригером и не уносить в код? а в модели просто эту информацию содержать и всё. Зачем нам это нужно, пусть DBA настроят правильно обновление сущностей как нам нужно

2024-10-31 09:24 UTC, AlexBimlnk commented on BookHub.API/Registrations/LogicExtensions.cs
> +            .AddSingleton<IScopedBookDescriptionService, ScopedBookDescriptionService>()
удалить

2024-10-31 09:26 UTC, AlexBimlnk requested changes
я поэтому и разбил на 2 задачи, чтобы 50+ файлов не смотреть.
Маленькие пры лучше чем большие, лучше добавить мало функциональности, но чище и прозрачнее, чем много сразу того, что непонятно что и зачем

2024-10-31 10:01 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/ScopedBookTopLevelDescriptionService.cs
> +        IServiceScopeFactory scopeFactory)
Ок

2024-10-31 10:02 UTC, Tigeroff2002 commented on BookHub.Models/CRUDS/CommandResult.cs
> +public enum CommandResult
```
        var result = await _service.AddBookAsync(
            (DomainAddBookParams)_converter.Convert(addParams),
            token);

        return result.CommandResult == CommandResult.Success
            ? Ok()
            : BadRequest(new FailureCommandResult
            {
                FailureMessage = result.FailureMessage!
            });
```
Ну это application логика получается - как еще контроллеру понять, что вернуть, 200 или 400

2024-10-31 10:03 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var storageBook = addBookParams is AddAuthorBookParams authorBookParams
Ну я так и сделал же. Нужно же сервису при добавлении личной книги знать иденфикатор айди автора - поэтому и есть разделение

2024-10-31 10:04 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [HttpPost]
Но там идет post запрос с контентом

2024-10-31 10:05 UTC, Tigeroff2002 commented on BookHub.API/Program.cs
> +app.UseSwagger().UseSwaggerUI();
+

2024-10-31 10:06 UTC, Tigeroff2002 commented on BookHub.Logic/Converters/BookParamsConverter.cs
> +                new UpdateBookAnnotationParams(
ну потому что я раньше делал, чем ты там что то добавил
Мне еще и доп модели заводить и парсить доменные модели параметров в это, потом как нибудь

2024-10-31 10:07 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +
оук

2024-10-31 10:07 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +            _logger.LogInformation(
Это уже реально споры ни о чем, пока у нас логов настолько мало, что можно все в инфо

2024-10-31 10:08 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +        catch (Exception ex)
Сервис не должен ActionResult какой то возвращать

2024-10-31 10:13 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookDescription.cs
> +public sealed record class BookDescription
действительно

2024-10-31 10:15 UTC, Tigeroff2002 commented
Ты ничего не разбивал, ты мне завел задачу на контроллер - который подразумевает сразу все

2024-10-31 10:16 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +        catch (Exception ex)
IOE перехвачу

2024-10-31 11:55 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var storageBook = addBookParams is AddAuthorBookParams authorBookParams
Я о том, чтобы не реализовывать сейчас добавление книги без автора. Потому что мы пока только личные книги и создаем

2024-10-31 11:56 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [HttpPost]
нужно подумать как сделать всё в соответствии с REST

2024-10-31 11:56 UTC, AlexBimlnk commented on BookHub.Logic/Converters/BookParamsConverter.cs
> +                new UpdateBookAnnotationParams(
Там как раз ничего заводить не надо. Там все на generic'ах

2024-10-31 12:00 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Models/Book.cs
> +    public long AuthorId { get; set; } = 0;
Мы не будем допускать книги без автора.

2024-10-31 12:01 UTC, AlexBimlnk commented on BookHub.Models/Books/Book.cs
> +        LastEditDate = DateTimeOffset.UtcNow;
Я не против, но просто это лишняя логика поддерживаемая, которую можно вынести на уровень базы и не заморачиваться.

2024-11-01 12:59 UTC, AlexBimlnk commented
Фиксани REST и добавление только с автором сделай пока. 
Из предложений - унести try-catch в контроллеры и там уже отдавать Ok/Bad и не городить лишних абстракций. К тому же api будет грязным когда оно возвращет какой-то "результат" команды, в объекте которого может быть что угодно. Это Rest http контроллеры, здесь не нужен подход с командами. У нас уже есть разные конечные точки, которые и разделяют логику путем get/post/put/delete запросов и роутинга данных (т.е. мы знаем что это за команда и с какими сущностями работает), в данном случае с книгой. А ты пытаешься сделать унифицированный response, а это не нужно, у нас для того контроллеры и эндпоинты разные что они уже делят всё.

2024-11-01 13:35 UTC, Tigeroff2002 commented on BookHub.Models/CRUDS/CommandResult.cs
> +public enum CommandResult
в контроллере не хочется заниматься перехватыванием исключений

2024-11-01 13:36 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        var storageBook = addBookParams is AddAuthorBookParams authorBookParams
Ясно

2024-11-01 13:56 UTC, Tigeroff2002 commented on BookHub.Models/CRUDS/CommandResult.cs
> +public enum CommandResult
Ладно

2024-11-01 13:56 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [HttpPost]
Сделал HTTPGET

2024-11-01 13:57 UTC, Tigeroff2002 commented on BookHub.Logic/Converters/BookParamsConverter.cs
> +                new UpdateBookAnnotationParams(
Потом исправлю

2024-11-01 13:57 UTC, Tigeroff2002 commented on BookHub.Logic/CrudServices/BookDescriptionService.cs
> +        catch (Exception ex)
Сложно больно - оставлю как есть пожалуй

2024-11-01 15:35 UTC, AlexBimlnk commented
Я про CommandResult, а не конкретные модели

2024-11-01 15:38 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +            return Ok(new SuccesfullCommandResult { Content = contractContent });
вот тут просто conttact и передать. Все. И не нужно ничего будет. Потом сделаешь

2024-11-01 15:38 UTC, AlexBimlnk approved these changes

2024-11-01 18:10 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +            return Ok(new SuccesfullCommandResult { Content = contractContent });
Я хочу чтобы +- все модели ответов были как то унифицированы
Хотя бы минимально там где подразумевается получение какого то контента - возвращалось поле content
А когда ошибка - поле failure_message

2024-11-01 18:12 UTC, WillzzArt approved these changes

2024-11-01 18:19 UTC, merged

2024-11-02 10:03 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +            return Ok(new SuccesfullCommandResult { Content = contractContent });
Я выше уже объяснял что унификация никакого смысла не имеет и только усложняет api. Потому что контент может быть разный иметь разную структуру и его описываешь object'om

> Это Rest http контроллеры, здесь не нужен подход с командами. У нас уже есть разные конечные точки, которые и разделяют логику путем get/post/put/delete запросов и роутинга данных (т.е. мы знаем что это за команда и с какими сущностями работает), в данном случае с книгой. А ты пытаешься сделать унифицированный response, а это не нужно, у нас для того контроллеры и эндпоинты разные что они уже делят всё.

2024-11-02 10:10 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +            return Ok(new SuccesfullCommandResult { Content = contractContent });
Плюс у тебя в сгенерированной схеме неправильно отражены response на эндпоинтах