#46 add books pagination
book-hub-umsp/book-hub-api pull request #49
Opened 2024-11-03 21:07 UTC by Tigeroff2002

Добавил методы АПИ для получения всех книг (точнее их превью - айди, айди автора, заголовок, жанр) - и тот же метод, только с пагинацией (клиент задает pageNumber и elementsInPage)

Сценарий там будет такой скорее всего - фронт сделает базовый запрос с pageNumber = 1 и elementsInPage = 5) - получит на него содержание и pagesTotal + elementsTotal - и от этого уже может двигаться, делая следующие запросы по командам пользователя - валидация вся вынесена в Pagination

#46 resolved

2024-11-03 22:07 UTC, AlexBimlnk commented
resolved надо в другом порядке писать, чтобы таски автоматичекски подцеплялись

2024-11-03 22:09 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [Route("get/pageNumber={pageNumber}&elementsInPage={elementsInPage}")]
не надо.
Просто используй атрибут FromQuery

2024-11-03 22:10 UTC, AlexBimlnk commented on BookHub.Abstractions/Logic/Services/IBookDescriptionService.cs
> +    public Task<IReadOnlyCollection<BookPreview>> GetAllBooksPreviews(
имеет смысл только с автором. Потому что иначе получать все книги просто невозможно (их слишком много)

2024-11-03 22:11 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Responces/GetBooksResponse.cs
> +public class GetBooksResponse
Уточнить надо. Слишком абстрактно звучит-

2024-11-03 22:11 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Responces/GetPaginedBooksResponse.cs
> +public sealed class GetPaginedBooksResponse : GetBooksResponse
PaginedBooksPreviewResponse

2024-11-03 22:11 UTC, AlexBimlnk commented on BookHub.Models/Books/BookPreview.cs
> +    {
Валидация

2024-11-03 22:12 UTC, AlexBimlnk commented on BookHub.Models/CRUDS/Requests/GetPaginedBooks.cs
> +public sealed class GetPaginedBooks
Если это общая модель с пагинацией. То как минимум нужно убрать Books.
А еще лучше и Get, оно не о чем не говорит. 
Лучше вроде Pagination или типа того

2024-11-03 22:20 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RepositoryBase.cs
> +    protected static Expression<Func<TData, bool>> CreateFilterWithLeftAndRightBound<TData, TKey>(
Все делается намного проще
MSDN: https://learn.microsoft.com/ru-ru/ef/core/querying/pagination#offset-pagination
Ef Core в действии: 
![изображение](https://github.com/user-attachments/assets/9932c9cd-3f29-4516-bfee-f77c14f278c4)

2024-11-03 22:21 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Responces/BookPreview.cs
> +    [JsonProperty("id", Required = Required.Always)]
добавь еще Required аннотации (чтоб свагер подхватывал)

2024-11-03 22:24 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    public async Task<IActionResult> GetPaginedBooksAsync(
описать api для сваггера не хочешь?

2024-11-03 22:25 UTC, AlexBimlnk requested changes
Посмотри примеры реализации пагинации и сделай по аналогии.
И общее кол-во элементов мы не будем знать, не будем вычислять и это не нужно

2024-11-04 15:16 UTC, wi1sp requested changes

2024-11-04 15:16 UTC, wi1sp commented on BookHub.Models/RequestSettings/Pagination.cs
> +        PagesTotal = elementsTotal % elementsInPage == 0
Не хочу душить но вроде можно сделать просто деление с округлением вверх, а не условие

2024-11-04 15:22 UTC, Tigeroff2002 commented on BookHub.Abstractions/Logic/Services/IBookDescriptionService.cs
> +    public Task<IReadOnlyCollection<BookPreview>> GetAllBooksPreviews(
Потом можно добавить - пока для теста хотя бы так

2024-11-04 15:26 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [Route("get/pageNumber={pageNumber}&elementsInPage={elementsInPage}")]
++

2024-11-04 15:32 UTC, Tigeroff2002 commented on BookHub.Models/CRUDS/Requests/GetPaginedBooks.cs
> +public sealed class GetPaginedBooks
Вынес в базу

2024-11-04 15:34 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    public async Task<IActionResult> GetPaginedBooksAsync(
Почему ты ставишь запрос в таком виде?
Что то описывать имеет смысл только после слияния изменений

2024-11-04 15:40 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    public async Task<IActionResult> GetPaginedBooksAsync(
Что?
Атрибуты Produces описать надо до слияния изменений.

2024-11-04 15:46 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RepositoryBase.cs
> +    protected static Expression<Func<TData, bool>> CreateFilterWithLeftAndRightBound<TData, TKey>(
Ну хз конечно, он неоптимизированно по любому это сделает, делая фильтрацию уже в приложении, а не в SQL
Но ладно, я не уверен что и мой вариант работает нормально

2024-11-04 15:56 UTC, Tigeroff2002 commented on BookHub.Abstractions/Logic/Services/IBookDescriptionService.cs
> +    public Task<IReadOnlyCollection<BookPreview>> GetAllBooksPreviews(
Хотя ладно, все равно ты смерджить не дашь так

2024-11-04 15:57 UTC, Tigeroff2002 commented on BookHub.Models/RequestSettings/Pagination.cs
> +        PagesTotal = elementsTotal % elementsInPage == 0
Напиши плиз, я не смог придумать

2024-11-04 16:41 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/QueryExtensions.cs
> +        pageNumber--;
??

2024-11-04 16:41 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/QueryExtensions.cs
> +        return query.Take(pageSize);
в одну строку можно записать

2024-11-04 16:43 UTC, AlexBimlnk commented on BookHub.Models/CRUDS/Requests/GetPaginedBooks.cs
> +public sealed class GetPaginedBooks : GetPaginedElementsBase
он нужен вообще?

2024-11-04 16:45 UTC, AlexBimlnk commented on BookHub.Logic/Services/BookDescriptionService.cs
> +        var elementsTotalCount = await _unitOfWork.Books.GetBooksTotalCountAsync(token);
мне не нравится идея вычислять постоянно для пагинации тотал. И возможно это не нужно.
Может пока просто оставить page number/elements in page и всё?

2024-11-04 16:49 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [Route("getPagined")]
я бы все делал с пагинацией, просто оставил бы одну точку get с пагинацией, и просто по умолчанию бы задал page number / elemetns

2024-11-04 16:49 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +            return BadRequest(new FailureCommandResultResponse { FailureMessage = ex.Message });
FromException?

2024-11-04 16:50 UTC, AlexBimlnk commented on BookHub.Logic/Services/BookDescriptionService.cs
> +        var elementsTotalCount = await _unitOfWork.Books.GetBooksTotalCountAsync(token);
Хотя ладно, пока так оставим.

2024-11-04 16:50 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        await Context.Books.AsNoTracking().CountAsync(token);
Наверняка LongCount нужно использовать

2024-11-04 16:52 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        Pagination pagination,
как то странно что получаю пагинацию мы уже знаем о тотальном кол-ве.
Я бы тотал, включал только в выходную response модель. Потому что она в домене по идее не нужна.

2024-11-04 16:53 UTC, AlexBimlnk commented on BookHub.Logic/Services/BookDescriptionService.cs
> +        GetPaginedBooks getPaginedBooks,
Тут просто модель pagination бы сделать которая несет в себе page number / elemets и всё.

2024-11-05 09:28 UTC, Tigeroff2002 commented on BookHub.Models/RequestSettings/Pagination.cs
> +        PagesTotal = elementsTotal % elementsInPage == 0
++

2024-11-05 09:29 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [Route("getPagined")]
По умолчанию нельзя задать - потому что фронт же может запрашивать разные странички

2024-11-05 09:30 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +            return BadRequest(new FailureCommandResultResponse { FailureMessage = ex.Message });
++

2024-11-05 09:34 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        Pagination pagination,
Она в домене используется - чтобы найти по elementsInPage кол-во страниц всего сколько - и типо свалидировать до запроса в БД номер страницы запрошенной

2024-11-05 09:37 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +        await Context.Books.AsNoTracking().CountAsync(token);
++

2024-11-05 09:38 UTC, Tigeroff2002 commented on BookHub.Logic/Services/BookDescriptionService.cs
> +        GetPaginedBooks getPaginedBooks,
Pagination собирается сервисом как раз - с учетом total count, который можно получить благодаря запросу к БД только - поэтому вряд ли

2024-11-05 11:59 UTC, AlexBimlnk commented on BookHub.Logic/Services/BookDescriptionService.cs
> +        GetPaginedBooks getPaginedBooks,
В том то и дело, что оно собирается только для Response и видимо только для того, чтобы вычислить количество страниц. А в самом коде доступа данных, в репозиториях - эти данные не нужны. Поэтому я думаю, что в домене это держать не нужно (тотал)

2024-11-05 12:01 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/QueryExtensions.cs
> +        pageNumber--;
Так все правильно. Если страница 1, то пропускать ничего не надо (т.е пропустить 0) и взять первые 5.
Мы же страницы не с нуля нумеруем

2024-11-05 12:03 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/QueryExtensions.cs
> +        pageNumber--;
Ты это -1 в skip добавь. А то непонятно почему вдруг страница запрашиваемая уменьшается

2024-11-05 12:06 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [Route("getPagined")]
Ну так да. Сделаем один эндпоинт поддерживающий query. Если он параметры будут переданы - возьмем из переданных, а если не будут переданы - поставим значение по умолчанию то есть 1 и 5 например

2024-11-05 13:04 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/RepositoryBase.cs
> +    protected static Expression<Func<TData, bool>> CreateFilterWithLeftAndRightBound<TData, TKey>(
В смысле? Это и есть Query для SQL

2024-11-05 13:39 UTC, AlexBimlnk commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +                .GetPageElements(pagination.PageNumber, pagination.ElementsInPage)
Тут еще перед тем как пагинировать - нужно сделать OrderBy по ключу. Иначе база может в произвольном порядке достать N элементов и тогда пагинация не определена

2024-11-05 13:41 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/RepositoryBase.cs
> +    protected static Expression<Func<TData, bool>> CreateFilterWithLeftAndRightBound<TData, TKey>(
Ну я уж не знаю, как оно там работает. Возможно, тут и без Expression он может задать запрос на SQL

2024-11-05 13:42 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/QueryExtensions.cs
> +        pageNumber--;
А не все ли равно, кто уменьшается - если это локальная переменная

2024-11-05 13:47 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/QueryExtensions.cs
> +        pageNumber--;
++

2024-11-05 13:47 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    public async Task<IActionResult> GetPaginedBooksAsync(
++

2024-11-05 13:48 UTC, Tigeroff2002 commented on BookHub.API/Controllers/BookDescriptionController.cs
> +    [Route("getPagined")]
А, дефолтные в запрос. Ок

2024-11-05 13:48 UTC, AlexBimlnk commented on BookHub.Models/RequestSettings/Pagination.cs
> +        if (elementsInPage % DEFAULT_ELEMENTS_IN_PAGE_REMINDER != 0)
как то странно жестко хардкодить обязательное кол-во элементов. Я думаю это не нужно. Пусть достает столько, сколько хочет? Но надо верхнюю границу поставить. Условно, чтобы нельзя было запросить сразу миллион. А там скажем книг 25-50 за запрос максимум.

2024-11-05 13:50 UTC, Tigeroff2002 commented on BookHub.Logic/Services/BookDescriptionService.cs
> +        GetPaginedBooks getPaginedBooks,
> Она в домене используется - чтобы найти по elementsInPage кол-во страниц всего сколько - и типо свалидировать до запроса в БД номер страницы запрошенной
Я выше комментарий отписал на этот счет - благодаря total идет валидация величины pageNumber

2024-11-05 13:51 UTC, Tigeroff2002 commented on BookHub.Storage/PostgreSQL/Repositories/BooksRepository.cs
> +                .GetPageElements(pagination.PageNumber, pagination.ElementsInPage)
++

2024-11-05 13:53 UTC, Tigeroff2002 commented on BookHub.Models/RequestSettings/Pagination.cs
> +        if (elementsInPage % DEFAULT_ELEMENTS_IN_PAGE_REMINDER != 0)
++

2024-11-05 13:56 UTC, Tigeroff2002 commented
Ну и думаю надо сделать по аналогии для получения всех пагинированных книг (так как мы понемножку их будем получать)

2024-11-05 13:57 UTC, wi1sp approved these changes

2024-11-05 15:23 UTC, AlexBimlnk commented on BookHub.API/Controllers/BookDescriptionController.cs
>      public async Task<IActionResult> UpdateBookAsync(
В будущем надо будет сделать фикс, чтобы пользователь мог менять только свои книги

2024-11-05 15:23 UTC, AlexBimlnk approved these changes

2024-11-05 18:15 UTC, wi1sp approved these changes

2024-11-05 18:18 UTC, merged