Feature/#43 add genres controller
book-hub-umsp/book-hub-api pull request #52
Opened 2024-11-05 18:33 UTC by Tigeroff2002

Добавил методы добавления нового жанра, получения всех жанров, удаления жанра
Они будут использоваться как под запросы при формировании страниц (или для администрации)

Добавил сравнение по мелкому шрифту без нижних подчеркиваний - так как хочется, что бы пользователь мог отправить название жанра в любом виде (PascalCase, camelCase, snake_case - и все грамотно могло быть сравнено с бд - где жанры будут храниться в snake_case)

По дефолту у книг стоит жанр 1 (default) - при удалении добавил триггер
@wi1sp прошу посмотреть миграцию

Также добавил проверку автора при обновлении и поправил нэйминг некоторых роутов

resolved #43

2024-11-05 22:00 UTC, AlexBimlnk commented on BookHub.Models/Books/BookGenre.cs
> +        // converting to snake_case to store in db in unificate format
зачем вообще хранить его в snake case в базе данных

2024-11-05 23:14 UTC, wi1sp requested changes

2024-11-05 23:14 UTC, wi1sp commented on Migrations/003_add_genre_remove_trigger.sql
> +REFERENCES genres (id);
тут надо добавить `ON DELETE SET DEFAULT` или что-то типа того. Даже если это дефолтное поведение стоит явно прописать.

2024-11-05 23:15 UTC, wi1sp commented on BookHub.Models/Books/BookGenre.cs
> +        // converting to snake_case to store in db in unificate format
ну потому что так в миграции прошлой было

2024-11-06 10:23 UTC, AlexBimlnk commented on BookHub.Models/Books/BookGenre.cs
> +        // converting to snake_case to store in db in unificate format
Мы же отказались от enum жанров. Значит в базе должны быть обычные строки. Зачем городить костыли тогда

2024-11-06 10:24 UTC, Tigeroff2002 commented on Migrations/003_add_genre_remove_trigger.sql
> +REFERENCES genres (id);
++

2024-11-06 10:28 UTC, wi1sp approved these changes

2024-11-06 11:14 UTC, Tigeroff2002 commented on BookHub.Models/Books/BookGenre.cs
> +        // converting to snake_case to store in db in unificate format
В БД мы хотим (по крайней мере я) чтобы был какой то унифицированный формат
Фронт нам может что угодно послать: PascalCase, Pascal Case, camelCase, snake_case - но в хранилище мы с одним и тем же будем дело иметь

2024-11-06 14:05 UTC, AlexBimlnk approved these changes
Заведи сразу задачу на рефакторинг. Где выпилить эти подчеркивания из базы и выпилить это конвертацию как минимум. 
А как максимум избавиться от миллиона моделей request/response и те что производятся в домене от них

2024-11-06 15:16 UTC, wi1sp approved these changes

2024-11-06 17:23 UTC, merged