Feature/#66 roles
book-hub-umsp/book-hub-api pull request #83
Opened 2024-11-10 16:52 UTC by Tigeroff2002

Добавил роли для пользователей на всех слоях (default и moderator)
Также снова вернул конфигурацию для администраторов - которых нужно будет настраивать через конфиги
Они могут в том числе обновлять роли пользователям - сделал такой метод в контроллере

Также еще сразу добавил пустой сервис для действий модератора - с проверкой на то, что пользователь им является

resolved #66

2024-11-10 17:52 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                        .Get<AdminAuthorizationConfiguration>()?.Admins ??
мы не будем делать конфиги из админов.

2024-11-10 17:54 UTC, AlexBimlnk commented on BookHub.Abstractions/Storage/Repositories/IUsersRepository.cs
> +    public Task UpdateUserRoleAsync(UpdateUserRoleParams updateUserRoleParams, CancellationToken token);
Этот метод не нужен. Это все отлично вписывется в один Update<UserRole>

2024-11-10 17:55 UTC, AlexBimlnk commented on BookHub.Models/CRUDS/Requests/Admins/UpdateUserRoleParams.cs
> +public sealed class UpdateUserRoleParams
удалить

2024-11-10 17:56 UTC, AlexBimlnk commented on BookHub.Models/Users/UserRole.cs
> +}
Ну если мы собираемся управлять ролями через контроллер, то видимо роль админа еще должна быть

2024-11-10 17:56 UTC, Tigeroff2002 commented on BookHub.Abstractions/Storage/Repositories/IUsersRepository.cs
> +    public Task UpdateUserRoleAsync(UpdateUserRoleParams updateUserRoleParams, CancellationToken token);
Ну нет - пользователь не должен иметь возможности сам свою роль свободно менять

2024-11-10 17:58 UTC, AlexBimlnk commented on BookHub.Models.Tests/Users/UserProfileInfo.Tests.cs
> +        profileInfo.Role.Should().Be(userRole);
ProfileInfo не включает не статус, не роли. Это в другой модели было (User)

2024-11-10 17:59 UTC, AlexBimlnk commented on BookHub.Models/Users/User.cs
Вот эту модель надо расширить моделью Role

2024-11-10 18:00 UTC, AlexBimlnk commented on BookHub.Logic/Services/ModeratorActionsService.cs
> +public sealed class ModeratorActionsService : IModeratorActionsService
не вижу сейчас смысла и пользы в этом сервисе

2024-11-10 18:03 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminActionsController.cs
> +    [HttpPatch("updateRole")]
[HttpPatch("user/{userId}/role)]

2024-11-10 18:05 UTC, AlexBimlnk commented on BookHub.Abstractions/Storage/Repositories/IUsersRepository.cs
> +    public Task UpdateUserRoleAsync(UpdateUserRoleParams updateUserRoleParams, CancellationToken token);
Причем тут пользователь. У нам метод в репозитории для обновления. Он один. И он на событиях.

2024-11-10 18:05 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Requests/Users/UpdateUserProfileInfoRequest.cs
> +using Newtonsoft.Json.Converters;
откуда эти юзинги появились?

2024-11-10 18:07 UTC, AlexBimlnk commented on BookHub.Logic/Services/ModeratorActionsService.cs
> +public sealed class ModeratorActionsService : IModeratorActionsService
И он вообще нигде не используется. Значит тем более эта вся логика не нужна здесь

2024-11-10 18:08 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                        .Get<AdminAuthorizationConfiguration>()?.Admins ??
Так что все это надо удалить

2024-11-10 18:09 UTC, AlexBimlnk commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                        .Get<AdminAuthorizationConfiguration>()?.Admins ??
Эти клеймы будут навешиваться в AuthHandler уже существующем. Если хочешь - можешь его изменить в рамках этого ПР.

2024-11-10 18:27 UTC, Tigeroff2002 commented on BookHub.API/Registrations/AuthentificationExtensions.cs
> +                        .Get<AdminAuthorizationConfiguration>()?.Admins ??
Убрал

2024-11-10 18:31 UTC, Tigeroff2002 commented on BookHub.Abstractions/Storage/Repositories/IUsersRepository.cs
> +    public Task UpdateUserRoleAsync(UpdateUserRoleParams updateUserRoleParams, CancellationToken token);
Ладно, тут так можно

2024-11-10 18:31 UTC, Tigeroff2002 commented on BookHub.Models/CRUDS/Requests/Admins/UpdateUserRoleParams.cs
> +public sealed class UpdateUserRoleParams
Модель для сервиса необходима

2024-11-10 18:31 UTC, Tigeroff2002 commented on BookHub.Models/Users/UserRole.cs
> +}
Добавил

2024-11-10 18:31 UTC, Tigeroff2002 commented on BookHub.Models.Tests/Users/UserProfileInfo.Tests.cs
> +        profileInfo.Role.Should().Be(userRole);
Ок, перенес в User

2024-11-10 18:32 UTC, Tigeroff2002 commented on migrations/004_add_user_role.down.sql
> +ALTER TABLE public.users DROP COLUMN role;
ок, не принципиально

2024-11-10 18:32 UTC, Tigeroff2002 commented on BookHub.Logic/Services/ModeratorActionsService.cs
> +public sealed class ModeratorActionsService : IModeratorActionsService
перенес в другую задачу пример

2024-11-10 18:33 UTC, Tigeroff2002 commented on BookHub.API/Controllers/AdminActionsController.cs
> +    [HttpPatch("updateRole")]
Там еще 3 параметр admin_id будет, так что пусть в модели будет
Нет смысла пользователю самому себе менять роль - это должен делать админ

2024-11-10 18:54 UTC, AlexBimlnk commented
И вообще у людей были вопросы по поводу того как это будет выглядеть. Не знаю зачем ты взялся её делать. 
Как выглядеть на уровне управления и на уровне базы. Так что пока пусть повисит конечно, но это.. Надо ещё чтоб @wi1sp объяснил что он хотел видеть

2024-11-10 18:58 UTC, AlexBimlnk commented on BookHub.Models/CRUDS/Requests/Admins/UpdateUserRoleParams.cs
> +public sealed class UpdateUserRoleParams
Почему не передавать в него сразу событие update? К чему это проксирование? 
К тому же в эндпоинте можно без JSON обойтись. Один параметр взять из route другой из query. Или оба из query

2024-11-10 19:03 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminActionsController.cs
> +    [HttpPatch("updateRole")]
А зачем параметр admin_id? Мы итак внутри запроса знаем кто его послал (пользователь авторизован). 
Я даже не знаю зачем на admin_id, но более того - его просто можно получить из IdentityFacade и никуда не передавать.

2024-11-10 19:16 UTC, AlexBimlnk commented on BookHub.API/Authentification/Configuration/Admin/AdminAuthorizationConfiguration.cs
> +public sealed class AdminAuthorizationConfiguration
лишнее

2024-11-10 19:16 UTC, AlexBimlnk commented on BookHub.API/Authentification/Configuration/Admin/AdminAuthorizationConfigurationValidator.cs
> +public sealed partial class AdminAuthorizationConfigurationValidator :
лишнее

2024-11-11 08:21 UTC, Tigeroff2002 commented
Я стал делать потому что она по списку была открыта. 
Да и какие вопросы - ты мне сам сказал, что вы там решили уже оказывается, что админы будут не из конфига браться
А собственно в этом случае кроме как енам расширять - вариантом больше нет
DBA больше ничего тебе не подскажут

2024-11-11 08:35 UTC, AlexBimlnk commented
@Tigeroff2002 А как коррелируют конфиги и наличие enum? Там были вопросы больше по поводу того, должна ли это быть отдельная таблица, если должна, то возможны ли мультироли и так далее. 
Задача просто заведена на будущее в беклог была. Ни на кого не назначена и не описана.

2024-11-11 08:38 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminActionsController.cs
> +    [HttpPatch("updateRole")]
Для этого специально был фасад заведен. Посмотри по коду, как это делается в user/me

2024-11-11 08:39 UTC, Tigeroff2002 commented on BookHub.API/Controllers/AdminActionsController.cs
> +    [HttpPatch("updateRole")]
В общем я сделал - вроде бы все классно выглядит

2024-11-11 08:42 UTC, AlexBimlnk commented
@Tigeroff2002 Раз начал делать, то придется здесь же тебе ещё расширить фасад identity. И поменять логику в userExistAuthHandler'e так, чтобы он добавлял клейм с ролью. А для этого нужно уже другой метод использовать из репозитория (получение целого юзера). 
А также завести константу в Auth.ClaimTypes

2024-11-11 08:45 UTC, AlexBimlnk commented
@Tigeroff2002 @WillzzArt 
Я буду помешать задачи, которые ещё не стоит брать в работу тегом "question"

2024-11-11 08:49 UTC, AlexBimlnk commented on BookHub.Contracts/REST/Requests/Users/UpdateUserProfileInfoRequest.cs
> +using Newtonsoft.Json.Serialization;
?

2024-11-11 08:51 UTC, AlexBimlnk commented on BookHub.Logic/Services/AdminActionsService.cs
> +        IHttpUserIdentityFacade userIdentityFacade,
Я бы убрал эту штуку на уровень контроллера.
Здесь бы добавил метод типа HasAdminPermission() : bool
В контроллере, если юзер не имеет привилегий
if (!_service.IsAdmin(_identity.UserId)){
return Forbidden 403.
}

//todo: change role

2024-11-11 08:52 UTC, AlexBimlnk commented on BookHub.Logic/Services/AdminActionsService.cs
> +        IHttpUserIdentityFacade userIdentityFacade,
И то это вряд ли нужно, потому что на контроллер можно политику навесить короче говоря. И вообще не проверять.

2024-11-11 08:53 UTC, AlexBimlnk commented on BookHub.Logic/Services/AdminActionsService.cs
> +        IHttpUserIdentityFacade userIdentityFacade,
А здесь оставить проверку типа, что нельзя изменить роль другим администраторам и что нельзя выставить роль администратора

2024-11-11 08:53 UTC, AlexBimlnk commented on BookHub.Models.Tests/Users/UserProfileInfo.Tests.cs
> +using System.ComponentModel;
?

2024-11-11 08:55 UTC, AlexBimlnk commented on BookHub.API/Controllers/AdminActionsController.cs
> +            _logger.LogInformation("Request was processed with failed result");
у нас же уже выше лог с ошибкой есть

2024-11-11 09:52 UTC, wi1sp requested changes
поправть ещё миграцию данилы с фаворитами 
все действия описал здесь #99

2024-11-11 09:52 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
Вообще насчёт ролей я думал сделать по сложнее систему по типу:
![image](https://github.com/user-attachments/assets/0029b4d6-35f3-49b2-96c8-eaa1606d1bd4)

Те у роли будут claims через котороые и разруливается доступ

Для оптимизация разрешаю где-нибудь enum юзнуть

2024-11-11 09:53 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
`default` конечно очень странное название для роли

2024-11-11 09:58 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
миграцию могу запровайдить

2024-11-11 10:22 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
во даже так могу сделать https://dbdiagram.io/d/BookHub-DB-673097efe9daa85acaec9066

2024-11-11 10:27 UTC, AlexBimlnk commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
claims это тип что? Разрешения для роли получается. Условно есть роль и есть разрешения. И роль может обладать коллекцией разрешений? Тогда это как минимум лучше policy назвать. 
И так ли это нужно вообще?

2024-11-11 11:32 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
ну насчёт нейминга мне в принципе без разницы
я думаю что потенциально лучше +- такую систему юзать, чтобы можно было управлять разрешениями для пользователей

2024-11-11 12:03 UTC, wi1sp commented on BookHub.Logic/Services/AdminActionsService.cs
> +        IHttpUserIdentityFacade userIdentityFacade,
> И то это вряд ли нужно, потому что на контроллер можно политику навесить короче говоря. И вообще не проверять.

согласен что просто надо политику накинуть на контроллер

2024-11-11 12:55 UTC, Tigeroff2002 commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
Схема очень сложная. Даже не понятно, что такое claim само по себе - а ты еще хочешь и в БД это сохранять
И еще мультироли какие то придумали. Вообще не понятно зачем
Все проще гораздо можно сделать: есть енам, у него три значения, они могут быть сравнены как инты
И если значение у какого то метода в бизнес логике хотя бы не больше текущей роли пользователя - то добавь возможность выполнять запрос, и все

2024-11-11 12:56 UTC, Tigeroff2002 commented on BookHub.Models.Tests/Users/UserProfileInfo.Tests.cs
> +using System.ComponentModel;
EnumException к твоему сведению от туда тянется

2024-11-11 12:59 UTC, Tigeroff2002 commented on BookHub.Logic/Services/AdminActionsService.cs
> +        IHttpUserIdentityFacade userIdentityFacade,
Я так и накидывал политику на контроллер - но меня как обычно попросили все изменить полностью
Сейчас опять добавить политику - но уже с клэймом каким то. В общем, давайте вы определитесь сначала сами, если все равно слушать меня не хотите и сами все решаете - а потом уже какой то фидбэк четкий

2024-11-11 13:25 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
- ну по сравнению с енаном, то да сложно
- ты и так к репозиторию обращаешься при проверке ролей
- за тем чтобы можно было роль настраивать

2024-11-11 13:26 UTC, wi1sp commented on BookHub.Logic/Services/AdminActionsService.cs
> +        IHttpUserIdentityFacade userIdentityFacade,
я лично про это подумал https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-8.0

2024-11-11 15:27 UTC, Tigeroff2002 commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
А зачем роль настраивать - и что под этим подразумевается?
Пока требований никаких не выдвигалось, кроме как то, что скорее всего будут роли юзера, модератора и админа

2024-11-11 17:35 UTC, wi1sp commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
это на будущее + разграниченее доступа привязано к клеймсу а не к роли
те есть функция и есть клеймс который нужен чтобы иметь доступ только к этой функции

2024-11-13 14:39 UTC, AlexBimlnk commented on BookHub.Models.Tests/Users/UserProfileInfo.Tests.cs
> +using System.ComponentModel;
Беда только в том, что EnumEx нигде не упоминается. Ведь в этом классе даже енамов нет.
Тебя не смущает что в класс добавился юзинг и код не изменился? Значит юзинг не нужен

2024-11-14 18:22 UTC, Tigeroff2002 commented on BookHub.Models.Tests/Users/UserProfileInfo.Tests.cs
> +using System.ComponentModel;
Ну вообще я думал, что в этом класс user role
А если юзинг добавился - то очевидно, что просто что добавилось/удалилось - это очень сложно контролировать, учитывая что это даже как варнинг не ставится

2024-11-14 18:24 UTC, Tigeroff2002 commented on migrations/002_create_user.up.sql
> +CREATE TYPE user_role AS ENUM ('default', 'moderator', 'admin');
Claim - это енам просто тогда, разве нет?

2024-11-15 10:57 UTC, closed without merging

2024-11-15 10:57 UTC, Tigeroff2002 commented
Переделаю в новой ветке, тут решать конфликты заебешься